### PR TITLE
Fmwpc smear update

### PR DESCRIPTION
**Pull request by staylorjlab**
Update smearing for FMWPC hits to reflect change from dE to q in the hit class and to add simulation of the drift time and the longitudinal diffusion (which smears the time).

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate/make_FMWPCSmearUpdate.log](https://halldweb.jlab.org/pull_request_test/halld_sim^FMWPCSmearUpdate/make_FMWPCSmearUpdate.log)
 Build report: [/work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate/report_FMWPCSmearUpdate.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FMWPCSmearUpdate/report_FMWPCSmearUpdate.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate

**Comment by staylorjlab** [comment]
Needs update to be merged in halld_recon before the build check will succeed.

**Comment by aaust** [comment]
I restarted the test build

**Comment by sdobbs** [comment]
Doesn't the test build use the nightly build for all other packages?

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate/make_FMWPCSmearUpdate.log](https://halldweb.jlab.org/pull_request_test/halld_sim^FMWPCSmearUpdate/make_FMWPCSmearUpdate.log)
 Build report: [/work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate/report_FMWPCSmearUpdate.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FMWPCSmearUpdate/report_FMWPCSmearUpdate.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate

**Comment by aaust** [comment]
Right. Let's try again tomorrow then.

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FMWPCSmearUpdate/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FMWPCSmearUpdate/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^FMWPCSmearUpdate/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate/make_FMWPCSmearUpdate.log](https://halldweb.jlab.org/pull_request_test/halld_sim^FMWPCSmearUpdate/make_FMWPCSmearUpdate.log)
 Build report: [/work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate/report_FMWPCSmearUpdate.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FMWPCSmearUpdate/report_FMWPCSmearUpdate.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate

**Comment by aaust** [comment]
Looks like hdgeant4 was not built last night.

**Comment by staylorjlab** [comment]
hdgeant4 was updated this morning to fill in the q information for the fmwpc.  However the exit status 127 is for hdgeant...

**Comment by staylorjlab** [comment]
... but the changes to HDGeant4 have not yet been merged into the master.

**Comment by markito3** [comment]
Last night's nightly for RHEL7 (which is used for the test) bombed in the middle with a "Connection to jlabl4 closed by remote host" in the middle of the build of halld_recon. So it never got to hdgeant4. So the test had no chance.

**Comment by markito3** [comment]
fired up the test again just now...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FMWPCSmearUpdate/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^FMWPCSmearUpdate/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate/make_FMWPCSmearUpdate.log](https://halldweb.jlab.org/pull_request_test/halld_sim^FMWPCSmearUpdate/make_FMWPCSmearUpdate.log)
 Build report: [/work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate/report_FMWPCSmearUpdate.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FMWPCSmearUpdate/report_FMWPCSmearUpdate.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^FMWPCSmearUpdate

**Review by aaust — APPROVED** [review]
as discussed in the CPP software meeting

**Pull request merged**
