### PR TITLE
More minor generalizations for gen_vec_ps and gen_amp

### PR DESCRIPTION
**Pull request by jrstevenjlab**
Remove default b1 resonances from seeded mass distribution and add Vec_ps_refl amplitude to gen_amp

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/make_vecps_gen_additions.log](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/make_vecps_gen_additions.log)
 Build report: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/report_vecps_gen_additions.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/report_vecps_gen_additions.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^vecps_gen_additions

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/make_vecps_gen_additions.log](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/make_vecps_gen_additions.log)
 Build report: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/report_vecps_gen_additions.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/report_vecps_gen_additions.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^vecps_gen_additions

**Comment by s6pepaul** [comment]
I think it needed a small tweak regarding the ReactionMechanism. Should work now.

**Review by s6pepaul — APPROVED** [review]

**Review by s6pepaul — APPROVED** [review]

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/make_vecps_gen_additions.log](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/make_vecps_gen_additions.log)
 Build report: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/report_vecps_gen_additions.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/report_vecps_gen_additions.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^vecps_gen_additions

**Comment by s6pepaul** [comment]
Error from the test build:

JANA >>OUTPUT_FILENAME: hd_root.root
JANA ERROR>>
JANA ERROR>>***ERROR : Couldn't find plugin "FCAL_online"!***
JANA ERROR>>***        make sure the JANA_PLUGIN_PATH environment variable is set correctly.
JANA ERROR>>***        To see paths checked, set PRINT_PLUGIN_PATHS config. parameter

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/make_vecps_gen_additions.log](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/make_vecps_gen_additions.log)
 Build report: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/report_vecps_gen_additions.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/report_vecps_gen_additions.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^vecps_gen_additions

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/make_vecps_gen_additions.log](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/make_vecps_gen_additions.log)
 Build report: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/report_vecps_gen_additions.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/report_vecps_gen_additions.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^vecps_gen_additions

**Comment by markito3** [comment]
The nightly build for RHEL7 is still not done. That was likely why the FCAL_online test failed. I resubmitted the test, and it got past FCAL_online, because that had been built, but then failed on hdgeant4, because hdgeant4 had not been built yet. I'll wait and resubmit once the build is done.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/make_vecps_gen_additions.log](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/make_vecps_gen_additions.log)
 Build report: [/work/halld/pull_request_test/halld_sim^vecps_gen_additions/report_vecps_gen_additions.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^vecps_gen_additions/report_vecps_gen_additions.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^vecps_gen_additions

**Pull request merged**
