### PR TITLE
Correct bug so that JEF can also run

### PR DESCRIPTION
**Pull request by igjaegle**
Correcting a bug introduce when limit on the photon energy range was set

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^ijaegle-fcal-mcsmear-correction/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle-fcal-mcsmear-correction/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ijaegle-fcal-mcsmear-correction/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle-fcal-mcsmear-correction/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle-fcal-mcsmear-correction/make_ijaegle-fcal-mcsmear-correction.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle-fcal-mcsmear-correction/make_ijaegle-fcal-mcsmear-correction.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle-fcal-mcsmear-correction/report_ijaegle-fcal-mcsmear-correction.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle-fcal-mcsmear-correction/report_ijaegle-fcal-mcsmear-correction.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle-fcal-mcsmear-correction

**Review by staylorjlab — APPROVED** [review]
This fixes a bug that prevented smearing of FCAL2 events.

**Comment by sdobbs** [comment]
Taking another look at this - what is the 8.?  Is it the block energy threshold?  If so, there should at least be a comment explaining this, but this sort of arbitrary constant is the sort of thing that should really be in the CCDB...

**Comment by igjaegle** [comment]
It is the energy range in GeV. I will add a comment for it.

tks ig.

**Pull request merged**
