### PR TITLE
* add description of how to get geometry from ccdb to usage [rtj]

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^better_usage_help_rtj/make_better_usage_help_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^better_usage_help_rtj/make_better_usage_help_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^better_usage_help_rtj/report_better_usage_help_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^better_usage_help_rtj/report_better_usage_help_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^better_usage_help_rtj

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^better_usage_help_rtj/make_better_usage_help_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^better_usage_help_rtj/make_better_usage_help_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^better_usage_help_rtj/report_better_usage_help_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^better_usage_help_rtj/report_better_usage_help_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^better_usage_help_rtj

**Comment by rjones30** [comment]
Can someone please fix this build failure? Maybe the disk is full?? -Richard

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^better_usage_help_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^better_usage_help_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^better_usage_help_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^better_usage_help_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^better_usage_help_rtj/make_better_usage_help_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^better_usage_help_rtj/make_better_usage_help_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^better_usage_help_rtj/report_better_usage_help_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^better_usage_help_rtj/report_better_usage_help_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^better_usage_help_rtj

**Review by markito3 — APPROVED** [review]
Looks good.

**Comment by markito3** [comment]
Don't know what the problem with the test was. Disk was not full.

**Pull request merged**
