### PR TITLE
Fix calculation of cm energy in case recoil!=target

### PR DESCRIPTION
**Pull request by s6pepaul**

### CODE REVIEW

**Comment by s6pepaul** [comment]
I didn't have a config file to test that it still works properly with a target other than LH2 bu I think it should work like this.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^genamp_cmenergy_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^genamp_cmenergy_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^genamp_cmenergy_fix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^genamp_cmenergy_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^genamp_cmenergy_fix/make_genamp_cmenergy_fix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^genamp_cmenergy_fix/make_genamp_cmenergy_fix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^genamp_cmenergy_fix/report_genamp_cmenergy_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^genamp_cmenergy_fix/report_genamp_cmenergy_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^genamp_cmenergy_fix

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^genamp_cmenergy_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^genamp_cmenergy_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^genamp_cmenergy_fix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^genamp_cmenergy_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^genamp_cmenergy_fix/make_genamp_cmenergy_fix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^genamp_cmenergy_fix/make_genamp_cmenergy_fix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^genamp_cmenergy_fix/report_genamp_cmenergy_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^genamp_cmenergy_fix/report_genamp_cmenergy_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^genamp_cmenergy_fix

**Review by aaust — APPROVED** [review]
Looks good. The generator does not work for nuclear targets, but this is a project for the future.

**Pull request merged**
