### PR TITLE
changed subtraction to addition in calculating the rotateY polarizati…

### PR DESCRIPTION
**Pull request by karthik18495**
Changed the sign in calculation of `rotateY`. There has to be an addition between `prod_angle` and `pol_Angle` instead of a negative sign. 

Changes has been applied to both CPU and GPU version of the `Vec_ps_refl` amplitude.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^prod_angle_calc/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^prod_angle_calc/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^prod_angle_calc/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^prod_angle_calc/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^prod_angle_calc/make_prod_angle_calc.log](https://halldweb.jlab.org/pull_request_test/halld_sim^prod_angle_calc/make_prod_angle_calc.log)
 Build report: [/work/halld/pull_request_test/halld_sim^prod_angle_calc/report_prod_angle_calc.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^prod_angle_calc/report_prod_angle_calc.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^prod_angle_calc

**Comment by mashephe** [comment]
Can you explain the rationale for this change?

**Comment by zisis0** [comment]
The behaviour of the neutral b1 fits needed it, but also analytical
calculations pointed to this. Perhaps we missed something, but it seemed
reasonable (Karthik, Justin, Zisis). 

Karthik can give more detail. 

Cheers, Zisis...

Sent from my iPhone

> On Aug 13, 2022, at 3:10 PM, Matthew Shepherd

**Comment by mashephe** [comment]
I looked at the code and I see the reason for the change.  The routine that calculates the angles is measuring the production angle w.r.t. phi = 0.  So, when the polarization angle is non-zero you need to add this non-zero offset to the difference.  (The same logic appears in line 78 of the TwoPiAngles code that Alex A. uses for the rho SDMEs.)  This is only needed if you intend to float the polarization angle in the fit.  Otherwise you can just calculate the correct angle in the helper routine.  

In fact that code (getomegapiAngles) has an argument for the angle, but it is not used.  It would be better if getomegapiAngles used polAngle correctly by setting eps = ( cos( polAngle ), sin( polangle ), 0 ) .  Your calling amplitude can still put a zero in for that value and it will function the same way.  As written, the function template appears to accept the polarization angle but the argument is then ignored.

**Comment by karthik18495** [comment]
Sorry for the late response, here is a write up summarizing why there should be a '+' sign in the calculation of the rotation angle. 

Also, I do agree that we can calculate the angles by setting `eps = (cos(polAngle), sin(polAngle), 0)`. However, we were hoping to perform a simultaneous fit with different orientations, Would that still work?  Also, If I may also point out that `getomegapiAngles` uses the `resonance` (omegapi) unit vector in `gamma p` rest frame in its calculation of `y` while `Zlm.cc` uses `-recoil` in its calculation. Should we make the calculation/definition of these unit vectors uniform across the board? 


[ProductionAngleWriteup.pdf](https://github.com/JeffersonLab/halld_sim/files/9337892/ProductionAngleWriteup.pdf)

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^prod_angle_calc/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^prod_angle_calc/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^prod_angle_calc/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^prod_angle_calc/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^prod_angle_calc/make_prod_angle_calc.log](https://halldweb.jlab.org/pull_request_test/halld_sim^prod_angle_calc/make_prod_angle_calc.log)
 Build report: [/work/halld/pull_request_test/halld_sim^prod_angle_calc/report_prod_angle_calc.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^prod_angle_calc/report_prod_angle_calc.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^prod_angle_calc

**Comment by jrstevenjlab** [comment]
Sorry for the very slow response on this.  The recent commit corrects what @mashephe  pointed out that the template function should allow for a polAngle to be provided, but by default we can set it to phi=0 and apply the correction in calcAmplitude.  

@karthik18495 using the opposite of the recoil or the meson system to define the y vector should be equivalent since we're using kinematically fit quantities, so I think these are already consistent in practice.  But if you prefer to make the calculation the same between Zlm and Vec_ps amplitudes that's fine with me.

**Review by jrstevenjlab — APPROVED** [review]
Since @karthik18495 submitted the PR I'll put my approval on the review here, but someone else should probably merge since I'm contributing to the PR as well.

**Review by mashephe — COMMENTED** [review]
I guess I'm reviewing after I merged, but yes, this is what I was suggesting in my comment.  Looks good to me.

**Comment by mashephe** [comment]
Karthik,

We just need a vector in the production plane to derive y -- it doesn't matter whether it is the resonance or recoil.  I think we're fine there.

Getting back to Phi, there is a difference between your approach and that in Zlm.  In the Zlm we calculate Phi (without an offset) in the calcUserVars routine using the polarization angle passed as an argument to the class.

In your amplitude, you calculate Phi up to an offset in calcUserVars.  Then in calcAmplitude you add the polarization angle offset back.  This is only needed if you intent to float the polarization angle in the fit.  In that case Phi must be re-evaluated when the parameter changes.  If you never intend to float the polarization angle in the fit, then it is sufficient just to compute Phi using the input polarization angle (as it is done in the Zlm code).

calcUserVars is called once at the start of the fit and lets you compute the angles once and store them.  calcAmplitude gets called anytime any of the parameters that the amplitude depend on changes.

Matt

**Pull request merged**
