### PR TITLE
updates to FCAL hit smearing

### PR DESCRIPTION
**Pull request by sdobbs**
Add functionality to merge energy depositions in FCAL crystals and light guides for FCAL hits including scale factor between the two. 

By default this behavior is enabled and the factor is pulled from the CCDB, but there are command line switches to modify this behavior as well.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/make_sdobbs_fcal_lightguide_updates.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/make_sdobbs_fcal_lightguide_updates.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/report_sdobbs_fcal_lightguide_updates.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/report_sdobbs_fcal_lightguide_updates.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/make_sdobbs_fcal_lightguide_updates.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/make_sdobbs_fcal_lightguide_updates.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/report_sdobbs_fcal_lightguide_updates.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/report_sdobbs_fcal_lightguide_updates.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates

**Comment by markdalton** [comment]
Maybe the message on line 241 of mcsmear.cc should indicate that the default is from CCDB?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/make_sdobbs_fcal_lightguide_updates.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/make_sdobbs_fcal_lightguide_updates.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/report_sdobbs_fcal_lightguide_updates.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates/report_sdobbs_fcal_lightguide_updates.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_fcal_lightguide_updates

**Review by markdalton — APPROVED** [review]
Looks good. This is a nice improvement for simulation of MIPs.  
Associated with the following study. https://halldweb.jlab.org/doc-private/DocDB/ShowDocument?docid=6234

**Pull request merged**
