### PR TITLE
add simu per tagger counter

### PR DESCRIPTION
**Pull request by igjaegle**
Add the possibility to simulate each tagger counter.
Usage:
1.  For a fixed energy
sd_compton bases-init.dbf test 8 1000 primex_tagm.txt 0
2. For the tagger
11.6061 GeV  (Be)
11.1671 GeV  (He)
a. microscope: 
sd_compton bases-init.dbf test 11.6061 10000 primex_tagm.txt 102
b. hodoscope:
sd_compton bases-init.dbf test 11.6061 10000 primex_tagh.txt 274

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^compt_corr/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^compt_corr/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^compt_corr/make_compt_corr.log](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/make_compt_corr.log)
 Build report: [/work/halld/pull_request_test/halld_sim^compt_corr/report_compt_corr.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/report_compt_corr.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^compt_corr

**Comment by andrsmit** [comment]
Igal, does this change to sd_compton.F require that the shell scripts also need to be modified (e.g. compton_prompt.sh)? If you run sd_compton with only 4 command line arguments like before, will it not be a problem?

**Comment by igjaegle** [comment]
Yes a 5 and 6th arguments are needed. But, if you set the 5th argument "whatever" and 6th argument to "1", you will be in the same condition than before

**Comment by andrsmit** [comment]
Yes, but if you merge these updates into the master branch then you can't run gen_primex_compton as is (which is fine, to be honest). The user has to run sd_compton (rather than gen_primex_compton with "run=true") to create the .hbook file and consequently the root file, and then gen_primex_compton should be called to convert the root file to hddm. I just want to make sure that is the intention.

**Comment by igjaegle** [comment]
Ah I forgot about it, let me change it

**Comment by igjaegle** [comment]
ok i did all the necessary changes, all scripts should work now.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^compt_corr/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^compt_corr/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^compt_corr/make_compt_corr.log](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/make_compt_corr.log)
 Build report: [/work/halld/pull_request_test/halld_sim^compt_corr/report_compt_corr.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/report_compt_corr.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^compt_corr

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^compt_corr/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^compt_corr/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^compt_corr/make_compt_corr.log](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/make_compt_corr.log)
 Build report: [/work/halld/pull_request_test/halld_sim^compt_corr/report_compt_corr.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/report_compt_corr.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^compt_corr

**Review by andrsmit — APPROVED** [review]

**Pull request merged**
