### PR TITLE
Double regge

### PR DESCRIPTION
**Pull request by ReBarsotti**
Adds amplitude class for Vincent's double regge model

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^doubleRegge/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^doubleRegge/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^doubleRegge/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^doubleRegge/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^doubleRegge/make_doubleRegge.log](https://halldweb.jlab.org/pull_request_test/halld_sim^doubleRegge/make_doubleRegge.log)
 Build report: [/work/halld/pull_request_test/halld_sim^doubleRegge/report_doubleRegge.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^doubleRegge/report_doubleRegge.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^doubleRegge

**Review by aaust — APPROVED** [review]
Looks good. If you ever want to use this amplitude in a fit, you should also register it in
https://github.com/JeffersonLab/halld_sim/blob/master/src/programs/AmplitudeAnalysis/fit/fit.cc

**Comment by ReBarsotti** [comment]
Thanks for the heads up, I did that as well!

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^doubleRegge/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^doubleRegge/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^doubleRegge/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^doubleRegge/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^doubleRegge/make_doubleRegge.log](https://halldweb.jlab.org/pull_request_test/halld_sim^doubleRegge/make_doubleRegge.log)
 Build report: [/work/halld/pull_request_test/halld_sim^doubleRegge/report_doubleRegge.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^doubleRegge/report_doubleRegge.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^doubleRegge

**Pull request merged**
