### PR TITLE
Vector pseudoscalar reflectivity amplitudes being used in omegapi analysis

### PR DESCRIPTION
**Pull request by jrstevenjlab**
This pull request adds vector-pseudoscalar reflectivity amplitudes, which rely strongly on the omegapi_amplitude in the helicity basis written by @amfodajlab.  These are currently being used in gen_omegapi, but could be extended to other final states. 

Also included here is ROOTDataReaderTEM from @amfodajlab which allows for binning in E_gamma, t, M from the AmpTools fit configuration file.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^binned_b1/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^binned_b1/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^binned_b1/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^binned_b1/make_binned_b1.log](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/make_binned_b1.log)
 Build report: [/work/halld/pull_request_test/halld_sim^binned_b1/report_binned_b1.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/report_binned_b1.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^binned_b1

**Comment by jrstevenjlab** [comment]
The build seems to be fine, but when the tests ran hdgeant4 failed with this error https://halldweb.jlab.org/pull_request_test/halld_sim%5ebinned_b1/tests-logs/hdgeant.txt 

hdgeant4: error while loading shared libraries: libDirac.so: cannot open shared object file: No such file or directory

@markito3: something to do with the recent inclusion of the Dirac library not getting included with the standard tests?

**Comment by mashephe** [comment]
Not a major issue, but if it is easy, I would recommend trying to preserve the convention of having class names vec_ps_refl start with a capital letter.  It helps distinguish Amplitude classes in that directory from helper routines like breakupMomentum.  (I realize this convention is also broken by the dblRegge amplitude in the same directory -- we should change that.)

**Comment by sdobbs** [comment]
test issue looks like a problem with the nightly build

**Comment by markito3** [comment]
Looking at it...

**Comment by mashephe** [comment]
Also, this data reader works, but I expect people will be looking to this as an example for how to do these things.  The data reader works by making two loops through the file.  The first time the number of passing events is counted.  The second time they are provide to the framework.  The counting is needed to do memory allocation by AmpTools.  It would be much better design if the data reader has a member function that returned a boolean if the current event pointed to by the various branch addresses passed the criteria.  As written the criteria are copy/pasted in both the constructor and the getEvent method.  If these diverge accidentally (update in one place but not elsewhere) then the result will be a potentially nasty problem in AmpTools where reading in data tramples memory in the case that the number of events is different from the number that the source supplies when being read.  Using a member function for the test ensures the test used to count will always be identical to the test used to deliver the event.

**Comment by jrstevenjlab** [comment]
Thanks for the comments.  Let me take a shot at addressing this before we merge.
-Justin

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^binned_b1/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^binned_b1/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^binned_b1/make_binned_b1.log](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/make_binned_b1.log)
 Build report: [/work/halld/pull_request_test/halld_sim^binned_b1/report_binned_b1.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/report_binned_b1.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^binned_b1

**Comment by markito3** [comment]
The nightly build was OK. It was the new environment set-up that was at fault. I had forgotten to add DIRACXX_HOME to LD_LIBRARY_PATH. That is done now for both bash and tcsh in Build Scripts. I re-tagged Build Scripts 2.8 on GitHub and re-deployed it at JLab and now the test succeeds.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^binned_b1/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^binned_b1/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^binned_b1/make_binned_b1.log](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/make_binned_b1.log)
 Build report: [/work/halld/pull_request_test/halld_sim^binned_b1/report_binned_b1.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/report_binned_b1.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^binned_b1

**Comment by jrstevenjlab** [comment]
@mashephe FYI, the latest commit changes the amplitude name to Vec_ps_refl and adds a member function to ROOTDataReaderTEM to be consistent in the loops over the input tree.  Hopefully this makes it a more useful example for future readers, but let me know if I missed something.

**Review by amfoda — APPROVED** [review]
Looks good.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^binned_b1/make_binned_b1.log](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/make_binned_b1.log)
 Build report: [/work/halld/pull_request_test/halld_sim^binned_b1/report_binned_b1.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/report_binned_b1.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^binned_b1

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^binned_b1/make_binned_b1.log](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/make_binned_b1.log)
 Build report: [/work/halld/pull_request_test/halld_sim^binned_b1/report_binned_b1.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^binned_b1/report_binned_b1.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^binned_b1

**Pull request merged**
