### PR TITLE
mcsmear oct2019 updates

### PR DESCRIPTION
**Pull request by sdobbs**
Two main changes to mcsmear:

* Add ability to toggle off the reading of information from the RCDB, for generic MC and other studies which don't correspond to real data
* Switch the way we load the TOF geometry depending on the available API, determined now by a #define.  This will allow us to properly use the latest halld_sim with older halld_recons.

### CODE REVIEW

**Comment by markito3** [comment]
Does this mean we have to maintain two builds of halld_sim, one for old data, one for new?

**Comment by sdobbs** [comment]
Well, this is something we should discuss in an Offline meeting, it depends
on the use cases that we want to support.  But as things stand, the master
of halld_sim, which was modified to support both the old and new TOF
configuration, will not compile with the reconstruction versions used to
produce 2017/2018 data.

**Comment by rjones30** [comment]
Hello Sean,

You wrote, "But as things stand, the master
of halld_sim, which was modified to support both the old and new TOF
configuration, will not compile with the reconstruction versions used to
produce 2017/2018 data."

Don't you mean, "will not compile with the hdds version"? I don't believe
my changes in halld_sim to accommodate the tof upgrade have any
dependencies on things that might have changed in halld_recon. Or are there
changes to halld_sim that go beyond my updates to hdgeant for the tof?

-Richard Jones

**Comment by sdobbs** [comment]
Hi Richard,

Yes, this is related to separate changes in halld_recon that were made
awhile ago, not your recent changes.

--Sean

**Comment by sdobbs** [comment]
> Does this mean we have to maintain two builds of halld_sim, one for old data, one for new?

Mark, I was checking the builds of halld_sim on OSG, don't you have a build for each halld_recon version we decide to support?  Then there would be no change, this just makes the code actually compile for older halld_recon versions, which it wouldn't before.

**Comment by markito3** [comment]
My concern comes from seeing some C pre-processor statements in the code. If those have to be controlled to get a build compatible with old code, then we have to specify three things to get the build we want: version number, halld_recon version used to build against, and pre-processor variable definitions. Granted that the latter two are correlated, but we don't record that correlation anywhere.

I'm happy to be talked out of the concern though. I might be missing something.

**Comment by sdobbs** [comment]
The #define that affects these is in halld_recon, so nothing special has to
be done to the build system.  Probably we need to define the first
"official" version of halld_recon that works well with the new TOF
geometry, then everything should work consistently.  The last tagged
halld_sim release doesn't actually build with the halld_recon version
corresponding to the last reconstruction of the 2017 data, which I think we
would like to have.  This case isn't in our regression tests, though.

**Pull request merged**
