### PR TITLE
change merging for fmwpc to be consistent with new version of event.xml

### PR DESCRIPTION
**Pull request by staylorjlab**

### CODE REVIEW

**Comment by staylorjlab** [comment]
This also changes the smearing itself  for the fmwpc to be consistent with the event.xml file

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^FmwpcHddmFix/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FmwpcHddmFix/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^FmwpcHddmFix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FmwpcHddmFix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^FmwpcHddmFix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^FmwpcHddmFix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^FmwpcHddmFix/make_FmwpcHddmFix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^FmwpcHddmFix/make_FmwpcHddmFix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^FmwpcHddmFix/report_FmwpcHddmFix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FmwpcHddmFix/report_FmwpcHddmFix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^FmwpcHddmFix

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^FmwpcHddmFix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FmwpcHddmFix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^FmwpcHddmFix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^FmwpcHddmFix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^FmwpcHddmFix/make_FmwpcHddmFix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^FmwpcHddmFix/make_FmwpcHddmFix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^FmwpcHddmFix/report_FmwpcHddmFix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FmwpcHddmFix/report_FmwpcHddmFix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^FmwpcHddmFix

**Review by aaust — APPROVED** [review]
looks reasonable

**Pull request merged**
