### PR TITLE
Better debug card doc rtj

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^better_debug_card_doc_rtj/make_better_debug_card_doc_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^better_debug_card_doc_rtj/make_better_debug_card_doc_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^better_debug_card_doc_rtj/report_better_debug_card_doc_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^better_debug_card_doc_rtj/report_better_debug_card_doc_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^better_debug_card_doc_rtj

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^better_debug_card_doc_rtj/make_better_debug_card_doc_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^better_debug_card_doc_rtj/make_better_debug_card_doc_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^better_debug_card_doc_rtj/report_better_debug_card_doc_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^better_debug_card_doc_rtj/report_better_debug_card_doc_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^better_debug_card_doc_rtj

**Comment by sdobbs** [comment]
I rebooted the test, just to check.  I think there was some collision.
I'll leave this unmerged to debug the test, but as Richard points out, the build test doesn't matter since this is just a configuration file change.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^better_debug_card_doc_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^better_debug_card_doc_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^better_debug_card_doc_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^better_debug_card_doc_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^better_debug_card_doc_rtj/make_better_debug_card_doc_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^better_debug_card_doc_rtj/make_better_debug_card_doc_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^better_debug_card_doc_rtj/report_better_debug_card_doc_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^better_debug_card_doc_rtj/report_better_debug_card_doc_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^better_debug_card_doc_rtj

**Review by sdobbs — APPROVED** [review]
looks good

**Pull request merged**
