### PR TITLE
Fix ordering of finalizeFit and writeSeed in fitMPI

### PR DESCRIPTION
**Pull request by jrstevenjlab**
Thanks to Dene for pointing this out.  This PR addresses issue https://github.com/JeffersonLab/halld_sim/issues/282

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^mpi_seed_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^mpi_seed_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^mpi_seed_fix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^mpi_seed_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^mpi_seed_fix/make_mpi_seed_fix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^mpi_seed_fix/make_mpi_seed_fix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^mpi_seed_fix/report_mpi_seed_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^mpi_seed_fix/report_mpi_seed_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^mpi_seed_fix

**Comment by maltealbrecht** [comment]
looks good.

**Review by maltealbrecht — APPROVED** [review]
Looks good.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^mpi_seed_fix/make_mpi_seed_fix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^mpi_seed_fix/make_mpi_seed_fix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^mpi_seed_fix/report_mpi_seed_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^mpi_seed_fix/report_mpi_seed_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^mpi_seed_fix

**Pull request merged**
