### PR TITLE
Unused variables commented out to supress warnings.

### PR DESCRIPTION
**Pull request by markito3**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^suppress_warnings_cobrems_MMI/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^suppress_warnings_cobrems_MMI/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^suppress_warnings_cobrems_MMI/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^suppress_warnings_cobrems_MMI/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^suppress_warnings_cobrems_MMI/make_suppress_warnings_cobrems_MMI.log](https://halldweb.jlab.org/pull_request_test/halld_sim^suppress_warnings_cobrems_MMI/make_suppress_warnings_cobrems_MMI.log)
 Build report: [/work/halld/pull_request_test/halld_sim^suppress_warnings_cobrems_MMI/report_suppress_warnings_cobrems_MMI.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^suppress_warnings_cobrems_MMI/report_suppress_warnings_cobrems_MMI.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^suppress_warnings_cobrems_MMI

**Review by rjones30 — COMMENTED** [review]
No, please don't do this. That breaks the code if I turn on COBREMS_GENERATOR_VERBOSITY. There must be another way to suppress bogus compiler warnings besides breaking the code.

**Review by rjones30 — CHANGES_REQUESTED** [review]
Please see my PR, fixes the same issue with compiler warnings without breaking the code in case verbosity is increased. If you approve my PR, this one can be discarded. -rtj

**Comment by markito3** [comment]
super-ceded by pull request #222

**Pull request closed without merging**
