### PR TITLE
correct bug, adding default target mass as proton

### PR DESCRIPTION
**Pull request by igjaegle**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by mashephe** [comment]
I just took a peak at these changes and maybe some previous changes also.  It seems there are unnecessary member data introduced into the ProductionMechanism class.  These hold the masses of various variables, but all that is needed is really the target and recoil masses.  It would be helpful if the changes kept the same style used in the existing code:  m_ denotes member data, so it is easy to see which variables are member data.  I think all of these:

 double kMproton,kMneutron,kMZ, kMPion, kMKaon, kMPi0;
  double kMDeuteron, kMHelium, kMC12;

can be removed.  There is no need for them to be member data because they are only referenced in the constructor.  It seem like the salient change from some time ago is to introduce a variable:  kMTarget.   My original class only had:  m_recMass  for the recoil because it was envisioned that the target was always a proton.  I understand now there are other use cases.  I would recommend a new variable:  m_targetMass instead of kMTarget (to use consistent style to enhance readability) and then remove all of the unnecessary member data.

**Comment by mashephe** [comment]
Another comment is that this class and its member functions are not constructed in a way that allows specifying an arbitrary combination of targets and recoil particles.  The original intent was that it was (only) a proton target and the recoil was either a neutron on proton.  The revisions that Igal has made rely on the assumption that target is always the same as the recoil, which is slightly different but still incomplete.

There is a new generator class FixedTargetGenerator that makes no assumptions other than what is in the title.  One can change target species and have varying recoils.  Also the beam four-vector can be arbitrarily changed, even to allow K_L beam.  Some of us are in the process of making a revision to gen_amp to use this generator.  Once that is in place, I suspect these ProductionMechanism classes and other stuff related to them will become obsolete.  They fail to handle other aspects of generation that are important for GlueX because customizing the target.

**Comment by igjaegle** [comment]
I removed all kM... variables except kMZ which is used later and added m_targetMass as requested

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Review by mashephe — APPROVED** [review]
Looks good

**Pull request merged**
