### PR TITLE
added the pdgtype into pythia-geant map to suppress Geant4 warnings

### PR DESCRIPTION
**Pull request by aaust**
@T-Britton: This file has to be ported to the MCWrapper repository

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/make_aaust_bggen_jpsi_pythia.log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/make_aaust_bggen_jpsi_pythia.log)
 Build report: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/report_aaust_bggen_jpsi_pythia.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/report_aaust_bggen_jpsi_pythia.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/make_aaust_bggen_jpsi_pythia.log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/make_aaust_bggen_jpsi_pythia.log)
 Build report: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/report_aaust_bggen_jpsi_pythia.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/report_aaust_bggen_jpsi_pythia.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/make_aaust_bggen_jpsi_pythia.log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/make_aaust_bggen_jpsi_pythia.log)
 Build report: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/report_aaust_bggen_jpsi_pythia.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/report_aaust_bggen_jpsi_pythia.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/make_aaust_bggen_jpsi_pythia.log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/make_aaust_bggen_jpsi_pythia.log)
 Build report: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/report_aaust_bggen_jpsi_pythia.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/report_aaust_bggen_jpsi_pythia.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/make_aaust_bggen_jpsi_pythia.log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/make_aaust_bggen_jpsi_pythia.log)
 Build report: [/work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/report_aaust_bggen_jpsi_pythia.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia/report_aaust_bggen_jpsi_pythia.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^aaust_bggen_jpsi_pythia

**Review by sdobbs — APPROVED** [review]
let's do it

**Pull request merged**
