### PR TITLE
add phaseoffset amplitude

### PR DESCRIPTION
**Pull request by jrstevenjlab**
Add amplitude which applies phase offset, useful for cases where two amplitudes are constrained to be the same apart from a common _real_ scale parameter.  This amplitude allows for a common phase difference in between constrained amplitudes.  Useful in for S and D waves for omegapi studies.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/make_jrs_phaseoffset.log](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/make_jrs_phaseoffset.log)
 Build report: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/report_jrs_phaseoffset.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/report_jrs_phaseoffset.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^jrs_phaseoffset

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/make_jrs_phaseoffset.log](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/make_jrs_phaseoffset.log)
 Build report: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/report_jrs_phaseoffset.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/report_jrs_phaseoffset.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^jrs_phaseoffset

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/make_jrs_phaseoffset.log](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/make_jrs_phaseoffset.log)
 Build report: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/report_jrs_phaseoffset.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/report_jrs_phaseoffset.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^jrs_phaseoffset

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/make_jrs_phaseoffset.log](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/make_jrs_phaseoffset.log)
 Build report: [/work/halld/pull_request_test/halld_sim^jrs_phaseoffset/report_jrs_phaseoffset.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^jrs_phaseoffset/report_jrs_phaseoffset.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^jrs_phaseoffset

**Review by mashephe — APPROVED** [review]

**Pull request merged**
