### PR TITLE
Exclude bad FCAL channels for PrimEx runs

### PR DESCRIPTION
**Pull request by somovalex**

### CODE REVIEW

**Comment by somovalex** [comment]
Exclude run-by-run determined bad channels listed in the /FCAL/block_quality table for PrimEx runs in order to make 
simulation consistent with reconstruction. Block_quality table was filled with the list bad and suspicious channels by Chandra 

Channels efficiency (FCAL/block_mc_efficiency) can be applied after excluding bad channels

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^primex_sim/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^primex_sim/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^primex_sim/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^primex_sim/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^primex_sim/make_primex_sim.log](https://halldweb.jlab.org/pull_request_test/halld_sim^primex_sim/make_primex_sim.log)
 Build report: [/work/halld/pull_request_test/halld_sim^primex_sim/report_primex_sim.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^primex_sim/report_primex_sim.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^primex_sim

**Review by andrsmit — APPROVED** [review]

**Comment by sdobbs** [comment]
Isn't this redundant with  /FCAL/block_mc_efficiency ?   I don't get the motivation here - it seems much more straightforward to just fill that table with whatever information is needed.

Also, PHOTON_BEAM/pair_spectrometer seems an odd place to keep track of an experiment-specific flag.

Finally, setting the probability for a bad channel to a negative value is really ugly - it works in this case, but it should really just be set to zero.

**Comment by somovalex** [comment]
We don't need to copy and duplicate tables. The same table with bad channels can be used
in both data and MC.  It is not clear whether using block_mc_efficiency is practical (there have
been discussions about this).

FCAL usually has a lot of bad channels during the run. The block_mc_efficiency has not been updated since
very long, i.e, it is not really used

94479  2017-12-13 15-18-58    2017-12-13 15-18-58     mc              30999L-inf      efficiency

--

Using negative values is as ugly as using numeric limits (at least it's clear that the channel is 'special')

                        // Tolerance for seeing if a number is near zero
                        // Could use std::numeric_limits::epsilon(), but that's probably too restrictive
                        const double maxAbsDiff = 1.e-8;

                        // If the hit efficiency is zero, then always reject it
                        // For floating point numbers, using the absolute difference to see if a
                        // number is consistent with zero is preferred.
                        // Reference: https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/
                        if( fabs(prob - 0.0) < maxAbsDiff )
                                return false;

                        // If the effiency is less than 0, then we always reject it
                        // This really shouldn't happen, though
                        if( prob < 0.0 )
                                return false;





________________________________

**Comment by markito3** [comment]
Maybe I should roll this one back until we get consensus on the approach?

**Comment by somovalex** [comment]
This is PrimEx implementation, it does not effect GlueX


________________________________

**Comment by markito3** [comment]
On the surface, it sounds like a general thing. How is it PrimEx specific?

**Comment by somovalex** [comment]
Masks are applied only for PrimEx runs, there is a check of the experiment type inside.

________________________________

**Comment by markito3** [comment]
But it sounds like it would be a good idea for all runs, no?

**Comment by somovalex** [comment]
People may consider to use it for other runs. But it will require some calibration efforts
(I mentioned this feature at the calorimeter meeting some time ago).

Actually people even don't try to update and follow the list of bad FCAL channels
for GlueX runs (see my previous comments), i.e. match MC with data

> FCAL usually has a lot of bad channels during the run. The block_mc_efficiency has not been
> updated since very long, i.e, it is not really used
> 94479  2017-12-13 15-18-58    2017-12-13 15-18-58     mc              30999L-inf      efficiency

We are very sensitive to bad channels in PrimEx, we cannot afford to do this.

At any rate, the new feature can be easily extended to all GlueX runs
(the interface is done through the CCDB)


________________________________

**Comment by markito3** [comment]
Yes. Thanks for pointing that out. You did mention that. Then my 
question would be why the block_mc_efficiency table is inadequate for 
PrimEx.

**Comment by igjaegle** [comment]
Mark, the block_quality is removing bad channels both in data and must therefore aslo be applied in simulation.

 
block_mc_efficiency is to match data/simulation efficiencies so by definistion is inadequate for PrimEX and GlueX in principle.

**Comment by somovalex** [comment]
I don't want to copy one table to another and duplicate entries
in CCDB. block_quality table is used in reconstruction DFCALHit and
contains a list of bad and suspicious channels for each run, which are
excluded (in PrimEx we had to go through all runs).
In fact one table should be used for bad channels in data and MC.








________________________________

**Comment by markito3** [comment]
I have to confess that I am confused about the details here. The two 
general points:

1) Bad channel handling seems to me not to depend on whether we have a 
PrimEx run type or not. One solution for all runs is less prone to 
misunderstandings and mis-configurations. I concede that one subgroup 
should not have to be responsible for back-annotating all runs to 
conform to some new and better scheme, but that is what a collaboration 
is for, no? Perhaps there is a staged approach that lets the current 
work continue on and brings in a complete solution in the future?

2) We should not be having a discussion about the correct approach after 
a pull request is merged. I would think we should be discussing the 
approach first, and then requesting the pull.

Here I am risking making a mountain out of a molehill, for sure. Seems 
worth discussing though.

**Comment by mashephe** [comment]
This would be a useful item for a calorimeter working group meeting.  It would be nice to understand the algorithm for identifying channels and we may consider then trying to apply it to all runs.  It would be useful to propagate these general improvements over all data if it is feasible.


On Jul 27, 2020, at 2:19 PM, Mark M. Ito <notifications@github.com<mailto:notifications@github.com>> wrote:


I have to confess that I am confused about the details here. The two
general points:

1) Bad channel handling seems to me not to depend on whether we have a
PrimEx run type or not. One solution for all runs is less prone to
misunderstandings and mis-configurations. I concede that one subgroup
should not have to be responsible for back-annotating all runs to
conform to some new and better scheme, but that is what a collaboration
is for, no? Perhaps there is a staged approach that lets the current
work continue on and brings in a complete solution in the future?

2) We should not be having a discussion about the correct approach after
a pull request is merged. I would think we should be discussing the
approach first, and then requesting the pull.

Here I am risking making a mountain out of a molehill, for sure. Seems
worth discussing though.

**Comment by igjaegle** [comment]
Matt, this was already presented by Chandra at the Feb 2020 Collaboration Meeting, https://halldweb.jlab.org/DocDB/0043/004340/001/gluexmeeting.pdf

**Comment by mashephe** [comment]
Thanks - is the code all available so it can, in principle, be just run over LED data from other runs?

It is a similar approach that was used at one point to write the block efficiency constant that people were also talking about in this thread, but we never had a good set of scripts for this so we could easily repeat it.  We should update those constants for other runs if the it is easy to just to execute this algorithm.

Matt


On Jul 27, 2020, at 2:32 PM, igjaegle <notifications@github.com<mailto:notifications@github.com>> wrote:



Matt, this was already presented by Chandra at the Feb 2020 Collaboration Meeting, https://halldweb.jlab.org/DocDB/0043/004340/001/gluexmeeting.pdf

**Comment by somovalex** [comment]
We have to check what Chandra committed to the repository. He spent quite time preparing masks for PrimEx runs.

________________________________

**Comment by igjaegle** [comment]
Yes, the Chandra put it on hd_utilities, https://github.com/JeffersonLab/hd_utilities/tree/master/fcalchannelfits

**Comment by somovalex** [comment]
Thanks for sending the link Igal,

In general, PrimEx has different than GlueX requirements on calibration precisions.
GlueX can  certainly benefit by using some of our procedures.



________________________________

**Comment by sdobbs** [comment]
Just to come back to my original observation, the split between using different tables for bad/inefficient channels MC and data comes from a historical discussion which is not really interesting or relevant to repeat.  I think that using /FCAL/block_quality in mcsmear is potentially a fine idea - I don't really have any strong feelings about it - but it seems like the sort of thing that we should try to have some coherent plan on since that would help everyone involved.

Also, while each particular run will have its own requirements, I personally feel like it's worth thinking carefully about how we add special cases for each of them to the code, or we will be in a real mess 5 years from now. =)

**Comment by somovalex** [comment]
Hi Sean,

Specific run or experiment conditions or different types of reconstruction should be identified by the run number
through the data base. Indeed we have to minimize  the variety of these conditions, but having some of them
is imminent. An example is handling of ADC thresholds in the microscope, which is enabled/disabled for different
run periods. The way I select PrimEx runs is through the experiment/run table. This way the implementation  is
backward compatible  (applies only specified run periods) and expandable.

---

In general the way  the block_mc_efficiency is implemented is wrong. It averages channel efficiency
over some run periods and neglects correlations between other sub-detectors (the effect can be negligible
for  GlueX but significant for PrimEx). I reported about this at one of the calorimeter meeting . . . the
response was - no manpower . . .  we do it in a different way in PrimEx.

Wrong (not updated) FCAL channel efficiencies (masks) are used in MC since run 30999L-inf

Cheers,
            Sasha


________________________________

**Comment by mashephe** [comment]
We clearly need to update those constants for other run periods.  We may opt for greater granularity/averaging for GlueX runs, which might not be acceptable for PrimEx for the reason Sasha notes.  I would be in favor of a common constant/implementation though.

----
This message was sent from my iPhone.

**Pull request merged**
