### PR TITLE
Evtgen ijaegle

### PR DESCRIPTION
**Pull request by igjaegle**
1/ primex_eta evtgen is modified to allow using other meson: \pi^0 and \eta'
2/ EtaRegge is modified in order to fold the Fermi motion using the impulse approximation

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by jonzarling** [comment]
Does this drop the feature to select a uniform |t| distribution in the config file? It looks like it might by my reading. I would like to keep that feature in any case.

I see that the option to generate a distribution flat in Mandelstam |t| again as a set of command line arguments. I originally implemented it this way, but found that didn't plug in as nicely for MCWrapper, hence specifying in the config instead.

Otherwise looks good to me.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by igjaegle** [comment]
I guess I used an older version of EtaRegge, I will re-implement your
uniform \t\ asap.

tks ig.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by staylorjlab** [comment]
I don't think the genEtaRegge config files belong in the gen_primex_eta_he4 directory.  

Also the $HALLD_SIM_HOME environment variable does not get expanded to its full path in the string, so some of the examples for the configuration files do not work out of the box.

**Comment by igjaegle** [comment]
Will correct that by tomorrow as well as re-including the Jon's |t| uniform

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by staylorjlab** [comment]
The thrown_FermiP histogram never gets created in genEtaRegge

**Comment by igjaegle** [comment]
Should be booked now.

tks ig.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Review by staylorjlab — APPROVED** [review]
I generated some events using both genEtaRegge and gen_primex_eta_he4 and things look like they are working now.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Pull request merged**
