### PR TITLE
Add a new compton event generator

### PR DESCRIPTION
**Pull request by igjaegle**
Implementation of Pawel's event generator.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^ijaegle_sd_compton/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_sd_compton/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ijaegle_sd_compton/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_sd_compton/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle_sd_compton/make_ijaegle_sd_compton.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_sd_compton/make_ijaegle_sd_compton.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle_sd_compton/report_ijaegle_sd_compton.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_sd_compton/report_ijaegle_sd_compton.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle_sd_compton

**Comment by somovalex** [comment]
looks oK from the first glance, will need to check more

**Review by somovalex — COMMENTED** [review]
looks Ok from the first glans, we'll need to check more

**Review by somovalex — APPROVED** [review]
Looks Ok

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^ijaegle_sd_compton/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_sd_compton/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ijaegle_sd_compton/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_sd_compton/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle_sd_compton/make_ijaegle_sd_compton.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_sd_compton/make_ijaegle_sd_compton.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle_sd_compton/report_ijaegle_sd_compton.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_sd_compton/report_ijaegle_sd_compton.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle_sd_compton

**Pull request merged**
