### PR TITLE
  Update to timting resolution values

### PR DESCRIPTION
**Pull request by KSaldan**
The update allows an option to use the original 0.4 ns timing resolution or use an energy dependent timing resolution where the parameters were measured from a timing resolution experiment. The timing resolution is used in mcsmear.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/make_FCAL_mcTimingSmearing_update.log](https://halldweb.jlab.org/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/make_FCAL_mcTimingSmearing_update.log)
 Build report: [/work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/report_FCAL_mcTimingSmearing_update.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/report_FCAL_mcTimingSmearing_update.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update

**Comment by KSaldan** [comment]
I fixed the error and the build compiles

**Comment by sdobbs** [comment]
if you push the fix to this branch, the test build will start again

**Comment by sdobbs** [comment]
Did you add the CCDB table to the master CCDB yet?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/make_FCAL_mcTimingSmearing_update.log](https://halldweb.jlab.org/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/make_FCAL_mcTimingSmearing_update.log)
 Build report: [/work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/report_FCAL_mcTimingSmearing_update.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/report_FCAL_mcTimingSmearing_update.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update

**Comment by sdobbs** [comment]
just one comment - the variable mc_config_t::FCAL_NEW_TIME_SMEAR needs to be given some default value.
then you can have one command-line switch which toggles the value

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/make_FCAL_mcTimingSmearing_update.log](https://halldweb.jlab.org/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/make_FCAL_mcTimingSmearing_update.log)
 Build report: [/work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/report_FCAL_mcTimingSmearing_update.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/report_FCAL_mcTimingSmearing_update.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update

**Review by sdobbs — APPROVED** [review]
good improvement, being included as option for further testing

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/make_FCAL_mcTimingSmearing_update.log](https://halldweb.jlab.org/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/make_FCAL_mcTimingSmearing_update.log)
 Build report: [/work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/report_FCAL_mcTimingSmearing_update.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update/report_FCAL_mcTimingSmearing_update.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^FCAL_mcTimingSmearing_update

**Pull request merged**
