### PR TITLE
Fix tof smearing bugs rtj

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^fix_tof_smearing_bugs_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_tof_smearing_bugs_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^fix_tof_smearing_bugs_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_tof_smearing_bugs_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^fix_tof_smearing_bugs_rtj/make_fix_tof_smearing_bugs_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_tof_smearing_bugs_rtj/make_fix_tof_smearing_bugs_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^fix_tof_smearing_bugs_rtj/report_fix_tof_smearing_bugs_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_tof_smearing_bugs_rtj/report_fix_tof_smearing_bugs_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^fix_tof_smearing_bugs_rtj

**Comment by jrstevenjlab** [comment]
Wow, great find Richard!  I noticed that in the master branch of halld_recon this DTOFGEOMETRY compiler switch is defined in 

https://github.com/JeffersonLab/halld_recon/blob/master/src/libraries/TOF/DTOFGeometry.h 

but in the older versions of halld_recon that we use to match the 2017-2018 reconstruction of data (which was used in Alex's example recon-2017_01-ver03.8), it is not defined

https://github.com/JeffersonLab/halld_recon/blob/recon-2017_01-ver03.8/src/libraries/TOF/DTOFGeometry.h

This seems to be the root of the problem, and explains why you didn't see a problem when using a newer software version (recon-2019_11-ver01.3) that does include the compiler flag 

https://github.com/JeffersonLab/halld_recon/blob/recon-2019_11-ver01.3/src/libraries/TOF/DTOFGeometry.h

So, do we want to add the definition of the compiler switch to the patched versions of halld_recon -> libraries/TOF/DTOFGeometry.h used for 2017-2018 simulation to be consistent with the master, or should we make the change proposed in this PR to define it directly in halld_sim?  

I don't think we've used the old version of the geometry for some time, so this may be a chance to clean out some legacy code.  Thoughts @zihlmann, @s6pepaul, @sdobbs, @aaust?

**Comment by rjones30** [comment]
Yes, there's more than one way to address it. While others are deciding
which way to go, it would be good to find out from analysts whether or not
the simulated pulse height in the TOF might be playing any role in the
acceptance calculation. Are thresholds being applied?
-Richard Jones

**Comment by jrstevenjlab** [comment]
Oh, I think I answered this on the issue #279  thread.  We can keep the discussion going there about the impacts and what to do once this fix is working.

**Comment by s6pepaul** [comment]
I don't have a particularly strong opinion on this to be honest. But it would feel more natural to me to have the switch in halld_sim if it is used here. As far as I could see it is not used anywhere in halld_recon?

**Comment by aaust** [comment]
I agree, it seems to be more elegant to define the switch here in halld_sim. I just wonder if this could create conflicts in case the value is defined differently in halld_recon. @sdobbs may decide, as he implemented this mechanism in the first place.

**Comment by sdobbs** [comment]
Wow, this was a trip down memory lane.  I think the original motivation for the switch was when we were still working out the details of halld_recon/halld_sim split, and clearly some of these changes didn't get propagated to the older compatibility branches (or it got overwritten at some point).

In any case, I don't think that just #defining DTOFGEOMETRY_VERSION is going to fix anything - the point of this is that the old DTOFGeometry objects don't have an interface for calls like `TOFGeom[0]->Get_NPlanes();`, so it's just not going to compile with these older versions.

I think that the right fix is to port the new TOF Geometry interface to the compatibility branches, and get rid of all of this old code.

**Comment by sdobbs** [comment]
I've made a different PR #289 based on my previous comment, and updated the halld_recon branch recon-2017_01-ver03-sim to work with that.  So if we prefer that solution, we can make a new recon-2017_01-ver03-sim tag.

We should still make sure the other merging bug that Richard identified gets fixed.

**Pull request closed without merging**
