### PR TITLE
Add BeamProperties

### PR DESCRIPTION
**Pull request by igjaegle**
Read beam flux histogram

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/make_ijaegle_primex_evt.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/make_ijaegle_primex_evt.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/report_ijaegle_primex_evt.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/report_ijaegle_primex_evt.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle_primex_evt

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/make_ijaegle_primex_evt.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/make_ijaegle_primex_evt.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/report_ijaegle_primex_evt.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/report_ijaegle_primex_evt.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle_primex_evt

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/make_ijaegle_primex_evt.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/make_ijaegle_primex_evt.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/report_ijaegle_primex_evt.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/report_ijaegle_primex_evt.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle_primex_evt

**Comment by markito3** [comment]
There was a problem with the nightly build that was causing the pull 
request tests to fail. This one should have succeeded the first time if 
not for the nightly build error. It look good now, build-wise.

**Comment by sdobbs** [comment]
Thanks for the clarification, @markito3

**Pull request merged**
