### PR TITLE
Evtgen ijaegle

### PR DESCRIPTION
**Pull request by igjaegle**
There are two modifications
1/ FCALsmearer is changed so that the FCAL energy range is scaled to the endpoint energy only is the endpoint energy is above 12 GeV
2/ Add Jackson Pybus's modified ALP generator with a generalized Form Factor as proposed in  https://journals.aps.org/prd/pdf/10.1103/PhysRevD.80.075018. For Carbon, the generalized Form Factor gives a theoretical cross-section 20% larger than the original and more robust Carbon Form Factor implementation.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Review by sdobbs — APPROVED** [review]
this seems reasonable, both the changes to the generator, and the change to FCAL smearing which should only affect studies for high-energy CEBAF running.  At some point we may want to take another look at these aspects of FCAL smearing

**Pull request merged**
