### PR TITLE
Correct photon beam energy for PrimEx

### PR DESCRIPTION
**Pull request by somovalex**

### CODE REVIEW

**Comment by sdobbs** [comment]
It would be good to know if this is a PrimEx-only development, or if the photon beam WG thinks that this is the method to apply to GlueX data as well.

Also, all the improvements going into the FCAL part of mcsmear (for example) are based on HDGeant4, so you may consider moving to that, or we should consider having a special CCDB variation for PrimEx

**Comment by sdobbs** [comment]
Matt,

Yes, I certainly agree, I should have been more clear that splitting the
code base is really not a good thing.  Hopefully we all will keep moving in
the same direction and so everyone can benefit from the latest work.

---Sean

**Comment by rjones30** [comment]
Sean,

The photon beam working group thinks that this approach that Sasha has
implemented for Primex is of more general use in GlueX. I have added
implementation of this to my work plan, and hope to get to in within the
next 2-3 weeks.

-Richard Jones

**Comment by somovalex** [comment]
Here is an email, which I sent to Sean (forgot to reply to everybody). All in all, 
the correct energy calculation can be easily applied to all GlueX data (if we decide
to do this).



Hi Sean,


At the moment I tested this feature for PrimEx data, but it is universal

in the sense that the correction will be applied if you set a run range

for the CCDB endpoint_calib table (but it requires tagger energies to be calibrated). 

 Though for GlueX it's going to be a relatively small correction, we can extend it to GlueX

runs in the future.


It's a good questions regarding moving to HDGeant4; I've not yet worked with

GlueX Geant4. We need to discuss.


Cheers,

       Sasha

**Comment by sdobbs** [comment]
Richard, Sasha, thanks for clearing this up!

**Pull request merged**
