### PR TITLE
Ecal update may2024

### PR DESCRIPTION
**Pull request by staylorjlab**
Removes dependence on DECALGeometry.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^ECALUpdateMay2024/make_ECALUpdateMay2024.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ECALUpdateMay2024/make_ECALUpdateMay2024.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ECALUpdateMay2024/report_ECALUpdateMay2024.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ECALUpdateMay2024/report_ECALUpdateMay2024.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ECALUpdateMay2024

**Comment by staylorjlab** [comment]
Needs updates from halld_recon for this to work.

**Comment by aaust** [comment]
I resubmitted it using today's nightly build

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^ECALUpdateMay2024/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ECALUpdateMay2024/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ECALUpdateMay2024/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ECALUpdateMay2024/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ECALUpdateMay2024/make_ECALUpdateMay2024.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ECALUpdateMay2024/make_ECALUpdateMay2024.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ECALUpdateMay2024/report_ECALUpdateMay2024.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ECALUpdateMay2024/report_ECALUpdateMay2024.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ECALUpdateMay2024

**Review by igjaegle — APPROVED** [review]

**Pull request merged**
