### PR TITLE
Zlm updates

### PR DESCRIPTION
**Pull request by maltealbrecht**
- Added GPU code for Zlm amplitude (by Matt)
- Added alternative options to initialize Zlm amplitude in cfg file to make use of polarization information in the AmpTools root trees

Changes are backwards compatible with "old" trees. 

There is a third option to use the Zlm amplitude, using a histogram of polarization vs. E. Usage of BeamProperties class is removed at the moment and replaced with reading from a plain root file. If we need it back, I can re-add that before merging into master.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^malte_Zlm_GPU/make_malte_Zlm_GPU.log](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Zlm_GPU/make_malte_Zlm_GPU.log)
 Build report: [/work/halld/pull_request_test/halld_sim^malte_Zlm_GPU/report_malte_Zlm_GPU.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Zlm_GPU/report_malte_Zlm_GPU.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^malte_Zlm_GPU

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^malte_Zlm_GPU/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Zlm_GPU/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^malte_Zlm_GPU/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Zlm_GPU/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^malte_Zlm_GPU/make_malte_Zlm_GPU.log](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Zlm_GPU/make_malte_Zlm_GPU.log)
 Build report: [/work/halld/pull_request_test/halld_sim^malte_Zlm_GPU/report_malte_Zlm_GPU.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Zlm_GPU/report_malte_Zlm_GPU.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^malte_Zlm_GPU

**Review by mashephe — COMMENTED** [review]
@jrstevenjlab :  this change removes the dependence on the BeamProperties class.  I prefer this for deploying fits outside of the GlueX software framework, but it would be helpful to have Justin take a look and verify no functionality has been lost.  One needs to provide the relevant ROOT file that contains polarization information.

**Comment by markito3** [comment]
This one got stuck in some strange state yesterday due to (a) broken nightly build and lilkely (b) problems with halldweb, which participates in the testing process. Note that I added a new blank line to README and added it to the branch to trigger the test again. I don't fully understand that nature of the stuckness...

**Comment by jrstevenjlab** [comment]
I don't see a loss of functionality by removing BeamProperties, which was created to have a common mechanism for passing polarization into the event generators with the beam configuration file (i.e. providing a ROOT histogram with the polarization vs energy).  However, the way it's implemented BeamProperties wasn't ever really effective in running fits.

@maltealbrecht's option 3 still allows for providing a histogram with polarization vs energy, but the histogram is specified in the AmpTools config file instead of the beam config file.  So I don't see an issue with this implementation and generally I like moving towards storing the polarization in the tree event-by-event.

**Comment by mashephe** [comment]
Thanks for reviewing this.  I agree that moving towards a strategy of storing polarization in the tree event-by-event is ideal.  I will ago ahead and approve this pull request.

**Review by mashephe — APPROVED** [review]

**Pull request merged**
