### PR TITLE
Restored the possibility to use some amplitudes with constant polarization

### PR DESCRIPTION
**Pull request by aaust**
Also added printout

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^aaust_amp_const_polfrac/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_amp_const_polfrac/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^aaust_amp_const_polfrac/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_amp_const_polfrac/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^aaust_amp_const_polfrac/make_aaust_amp_const_polfrac.log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_amp_const_polfrac/make_aaust_amp_const_polfrac.log)
 Build report: [/work/halld/pull_request_test/halld_sim^aaust_amp_const_polfrac/report_aaust_amp_const_polfrac.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_amp_const_polfrac/report_aaust_amp_const_polfrac.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^aaust_amp_const_polfrac

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^aaust_amp_const_polfrac/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_amp_const_polfrac/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^aaust_amp_const_polfrac/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_amp_const_polfrac/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^aaust_amp_const_polfrac/make_aaust_amp_const_polfrac.log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_amp_const_polfrac/make_aaust_amp_const_polfrac.log)
 Build report: [/work/halld/pull_request_test/halld_sim^aaust_amp_const_polfrac/report_aaust_amp_const_polfrac.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_amp_const_polfrac/report_aaust_amp_const_polfrac.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^aaust_amp_const_polfrac

**Review by markdalton — APPROVED** [review]
Thanks, this is useful.

**Comment by jrstevenjlab** [comment]
Just a comment that if you use `PolarizationMagnitude 0.4` in your beam config file, a single bin histogram should be created internally in the BeamProperties class with this value of 0.4 for the polarization for all beam energies.  This was intended to be used to generate or fit with a constant polarization, although not a lot of testing was done on the fitting portion.

It may be easier for scripting purposes to try many fits with varied polarizations by setting this constant polarization in the AmpTools config file where the amplitude is called.  I don't have a particular preference, but both seem to be a reasonable option unless the one I described is broken, in which case I'd like to fix it.

**Comment by markdalton** [comment]
I'm agnostic about the method. It sounds like they both should work.

**Comment by aaust** [comment]
Thanks Justin, I was not aware of that function. And I don't think it is working. I tried to add the magnitude to the automatically generated local_beam.conf, but the program is calling cobrems and the polarization does not come out a constant.

**Comment by jrstevenjlab** [comment]
Ok, I'll look at why that's broken, but that'll be separate from this PR.

**Pull request merged**
