### PR TITLE
Simple s-channel generator, where the decays are handled by decay_evtgen

### PR DESCRIPTION
**Pull request by sdobbs**
Requested by several people

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_schannel/make_sdobbs_schannel.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_schannel/make_sdobbs_schannel.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_schannel/report_sdobbs_schannel.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_schannel/report_sdobbs_schannel.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_schannel

**Comment by sdobbs** [comment]
need to merge in some SBMS changes from last night, retrying...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^sdobbs_schannel/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_schannel/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^sdobbs_schannel/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_schannel/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_schannel/make_sdobbs_schannel.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_schannel/make_sdobbs_schannel.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_schannel/report_sdobbs_schannel.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_schannel/report_sdobbs_schannel.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_schannel

**Comment by jrstevenjlab** [comment]
Sorry, I didn't catch that one in all the updates.

**Comment by aaust** [comment]
This generator is dependent on evtgen. As the libraries and decay_evtgenq, it should only be built if EVTGENDIR is defined:

https://github.com/JeffersonLab/halld_sim/blob/master/src/programs/Simulation/SConscript

**Comment by sdobbs** [comment]
My bad, thanks for pointing this out

**Pull request merged**
