### PR TITLE
Evtgen ijaegle

### PR DESCRIPTION
**Pull request by igjaegle**
1/ Add free neutron target choice for genScalerRegge
2/ Allow quasifree production for the Nuclear Incoherent case for gen_primex_eta_he4

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by staylorjlab** [comment]
Using the default configuration file I get the following errors when running 
gen_primex_eta_he4 -hd tst.hddm -e config_primex_eta_he4_2g.cfg
opening HDDM file: tst.hddm

 ---------------------------------------- 
 Read File : "config_primex_eta_he4_2g.cfg"
rfile /work/halld/home/ijaegle/he4_eta_primakoff/PRIMEX-D_eta_he4-corrected.root
histo xs_tot_vs_egamb
decay eta->2g
target Helium
ParticleMass: Error: Unknown particle type 1882005618, returning HUGE_VAL...
ParticleMass: Error: Unknown particle type 1882005618, returning HUGE_VAL...
ParticleMass: Error: Unknown particle type 1701996660, returning HUGE_VAL...
ParticleCharge: Error: Unknown particle type 1882005618, returning 0...

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by aaust** [comment]
@staylorjlab Did you have a chance to test it again? The automated test just failed because two commits came in shortly after one another

**Comment by staylorjlab** [comment]
genScalarRegge runs without trouble with the fixes.

gen_primex_eta_he4 -hd tst.hddm -e config_primex_eta_he4_2g.cfg  runs but there is a strange message in the output:
Meson mass inf pdg 0

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Comment by staylorjlab** [comment]
Appended below is the output of gen_primex_eta_he4 -e config_primex_eta_he4_2g.cfg -hd tst.hddm after the latest fixes.
The string comparison does not work.  I think you have to do something like m_meson.EqualTo("Eta")

 ---------------------------------------- 
 Read File : "config_primex_eta_he4_2g.cfg"
rfile /work/halld/home/ijaegle/he4_eta_primakoff/PRIMEX-D_eta_he4-corrected.root
histo xs_tot_vs_egamb
meson Eta
Wrong meson choice, please choose between Eta, EtaPrime, or Pi0

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/make_evtgen-ijaegle.log)
 Build report: [/work/halld/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^evtgen-ijaegle/report_evtgen-ijaegle.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^evtgen-ijaegle

**Review by staylorjlab — APPROVED** [review]
Looks okay.

gen_primex_eta_he4 now runs with the provided configuration file with the latest changes.

**Pull request merged**
