### PR TITLE
Fix hdgeant crash in gmicap rtj

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/make_fix_hdgeant_crash_in_gmicap_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/make_fix_hdgeant_crash_in_gmicap_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/report_fix_hdgeant_crash_in_gmicap_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/report_fix_hdgeant_crash_in_gmicap_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/make_fix_hdgeant_crash_in_gmicap_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/make_fix_hdgeant_crash_in_gmicap_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/report_fix_hdgeant_crash_in_gmicap_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/report_fix_hdgeant_crash_in_gmicap_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/make_fix_hdgeant_crash_in_gmicap_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/make_fix_hdgeant_crash_in_gmicap_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/report_fix_hdgeant_crash_in_gmicap_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/report_fix_hdgeant_crash_in_gmicap_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/make_fix_hdgeant_crash_in_gmicap_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/make_fix_hdgeant_crash_in_gmicap_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/report_fix_hdgeant_crash_in_gmicap_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj/report_fix_hdgeant_crash_in_gmicap_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^fix_hdgeant_crash_in_gmicap_rtj

**Review by aaust — APPROVED** [review]
Seems reasonable.

**Comment by aaust** [comment]
@rjones30 I missed these compiler warnings:
```
programs/Simulation/HDGeant/hadevv.F:2160.5:

32507          CONTINUE
     1
Warning: Label 32507 at (1) defined but not used
programs/Simulation/HDGeant/hadevv.F:2973.4:

9999  CONTINUE
    1
Warning: Label 9999 at (1) defined but not used
programs/Simulation/HDGeant/hadevv.F:129.17:

         ISAM1 = 1.D0 + 3.D0*RNDM(1)
                 1
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1)
programs/Simulation/HDGeant/hadevv.F:147.17:

         ISAM2 = 1.D0 + 3.D0*RNDM(1)
                 1
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1)
programs/Simulation/HDGeant/hadevv.F:186.20:

            ISAM3 = 1.D0 + 2.D0*RNDM(1)
                    1
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1)
programs/Simulation/HDGeant/hadevv.F:197.20:

            ISAM4 = 1.D0 + 3.D0*RNDM(1)
                    1
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1)
programs/Simulation/HDGeant/hadevv.F:250.20:

            ISAM3 = 1.D0 + 2.D0*RNDM(1)
                    1
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1)
programs/Simulation/HDGeant/hadevv.F:282.20:

            ISAM4 = 1.D0 + 3.D0*RNDM(1)
                    1
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1)
programs/Simulation/HDGeant/hadevv.F:340.17:

         ISAM5 = 1.D0 + 3.D0*RNDM(1)
                 1
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1)
programs/Simulation/HDGeant/hadevv.F:358.17:

         ISAM6 = 1.D0 + 3.D0*RNDM(1)
                 1
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1)
programs/Simulation/HDGeant/hadevv.F:638.20:

            IRNDM = 1.D+00 + RNDM (1)
                    1
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1)
```

**Comment by rjones30** [comment]
These implicit conversions are perfectly fine. They are part of the f77
standard. It seems like the esthetic of clean fortran code has changed
since the days when I wrote fortran, when such conversions were considered
elegant -- like a kind of proto-polymorphism before polymorphism was a
thing.
-Richard

**Pull request merged**
