### PR TITLE
Fix logic that denotes failed fits

### PR DESCRIPTION
**Pull request by aaust**
This addresses issue #255 , which was brought up by @lan13005

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^aaust_fit_failed/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_fit_failed/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^aaust_fit_failed/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_fit_failed/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^aaust_fit_failed/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_fit_failed/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^aaust_fit_failed/make_aaust_fit_failed.log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_fit_failed/make_aaust_fit_failed.log)
 Build report: [/work/halld/pull_request_test/halld_sim^aaust_fit_failed/report_aaust_fit_failed.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_fit_failed/report_aaust_fit_failed.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^aaust_fit_failed

**Comment by aaust** [comment]
Test failed due to broken hdgeant4 in nightly build. Fixed and redelivered.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^aaust_fit_failed/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_fit_failed/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^aaust_fit_failed/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_fit_failed/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^aaust_fit_failed/make_aaust_fit_failed.log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_fit_failed/make_aaust_fit_failed.log)
 Build report: [/work/halld/pull_request_test/halld_sim^aaust_fit_failed/report_aaust_fit_failed.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_fit_failed/report_aaust_fit_failed.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^aaust_fit_failed

**Review by jrstevenjlab — APPROVED** [review]
Fixes the logic bug

**Pull request merged**
