### PR TITLE
* update the tagger smearing to add error to the tagged photon

### PR DESCRIPTION
**Pull request by rjones30**
energy in both the microscope and hodoscope. [rtj]

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/make_improve_tagged_photon_energy_smearing_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/make_improve_tagged_photon_energy_smearing_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/report_improve_tagged_photon_energy_smearing_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/report_improve_tagged_photon_energy_smearing_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj

**Comment by sdobbs** [comment]
Hi Richard,

Thanks a lot for these changes - I agree that this is the way to go, but could we please default to the energy being the center of the corresponding tagger counter?  This is how it is done in the reconstruction, so if we want to change the default behavior, we should do it in a coordinated way, IMO.

---Sean

**Comment by rjones30** [comment]
Sean, that would be a change to what we have done since the beginning of
the simulation until now. Are you sure you want to make this change now?
-Richard Jones

**Comment by sdobbs** [comment]
Maybe I am confused?  My understanding was that we had been using the tagger hit energies from HDGeant4, and looking in GlueXPseudoDetectorTAG in that package, the center of the counters is being used.

**Comment by rjones30** [comment]
Sean,

Ok, I see it. The E in taggerTruthHit is the original beam photon energy,
but the one loaded into the microChannel E parameter is the instantaneous
center of the tagger bin energy for that run being simulated. In
retrospect, I guess this latter E parameter should not exist, as it will be
different from the real data and random events, as the MC, randoms, and
real data for a given run are all different vintages of our ccdb +
processing chain. It is ugly, but I suppose we could leave it that way if
people are used to it. Are you sure this is what we want? Randomizing the
reported E value for the column would make this inconsistency unobservable.

-Richard J.

**Comment by sdobbs** [comment]
Richard,

I agree that all of this would be more straightforward if we just stored information on the tagger counter and not the energy.  That being said, we are currently determining the photon energy from the tagger counter at runtime in all cases except for hddm_s data.  Practically this only affects the random triggers that are sitting on disk, for the vast majority of cases.  So, I think that recalculating the tagged photon energies in mcsmear is a reasonable solution to the problem.

That being said, I still think that they should default to the midpoint of the counter, since that's what we've been doing consistently in all other cases.  Maybe it doesn't make a difference in the end... but at the current point I would prefer not to introduce a new possible source of inconsistencies.

**Comment by rjones30** [comment]
Sean, ok let me introduce this randomization as an option, leaving the
default behavior as you describe. Is that a good solution?
-Richard Jones

**Comment by sdobbs** [comment]
I think that's a good solution - do you mean adding the randomization as a command-line option?  That would help testing it a lot.

**Comment by rjones30** [comment]
Sean, yes as a commandline option, defaults to false. Look for a PR on
halld_sim shortly.
-rtj

**Comment by rjones30** [comment]
Sean, my PR to halld_sim has been updated as we discussed. -rtj

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/make_improve_tagged_photon_energy_smearing_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/make_improve_tagged_photon_energy_smearing_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/report_improve_tagged_photon_energy_smearing_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/report_improve_tagged_photon_energy_smearing_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj

**Comment by rjones30** [comment]
Should this PR be cancelled? -rtj

**Comment by rjones30** [comment]
Cancelling this PR. -rtj

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/make_improve_tagged_photon_energy_smearing_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/make_improve_tagged_photon_energy_smearing_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/report_improve_tagged_photon_energy_smearing_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/report_improve_tagged_photon_energy_smearing_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj

**Comment by rjones30** [comment]
Peter, would you like to reopen that PR? If so, I will need to merge in the
changes since then and resubmit.
-Richard Jones

**Comment by s6pepaul** [comment]
Yes please, if you don't mind!

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/make_improve_tagged_photon_energy_smearing_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/make_improve_tagged_photon_energy_smearing_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/report_improve_tagged_photon_energy_smearing_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/report_improve_tagged_photon_energy_smearing_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj

**Comment by rjones30** [comment]
Peter,

It seems that someone checked in a broken PR, now halld_sim will not build
on the std gcc-4.8.5 platform. Here is the error;

Installing
[/home/halld/halld_sim/Linux_CentOS7-x86_64-gcc4.8.5/bin/genScalarRegge]
programs/AmplitudeAnalysis/fit/fit.cc: In function 'void
runParScan(ConfigurationInfo*, bool, bool, int, std::string, std::string)':
programs/AmplitudeAnalysis/fit/fit.cc:199:9: error: 'class
AmpToolsInterface' has no member named 'reinitializePars'
     ati.reinitializePars();
         ^
-Richard Jones

**Comment by s6pepaul** [comment]
You merged in a devel branch which I am not sure about what exactly it is. I only see that the two pull request that got merged since you opened this one passed their tests. So I am not quite sure what happened here.

**Comment by s6pepaul** [comment]
I pulled the branch and was able to build this myself. Maybe the issue is with the test.

**Comment by rjones30** [comment]
Peter,

Yes, the devel branch was my own, the one we are talking about. The master
branch contains this broken stuff related to genScalarRegge, here it is
again. Can you fix this, or roll it back?

-Richard J.

Installing
[/home/halld/halld_sim/Linux_CentOS7-x86_64-gcc4.8.5/bin/genScalarRegge]
programs/AmplitudeAnalysis/fit/fit.cc: In function 'void
runParScan(ConfigurationInfo*, bool, bool, int, std::string, std::string)':
programs/AmplitudeAnalysis/fit/fit.cc:199:9: error: 'class
AmpToolsInterface' has no member named 'reinitializePars'
     ati.reinitializePars();
         ^

**Comment by rjones30** [comment]
Peter, can you check on why the test is failing? I tried to click on the
link in the email, but it goes nowhere.
-Richard Jones

**Comment by s6pepaul** [comment]
On it.
The line that causes the error you see was pulled with https://github.com/JeffersonLab/halld_sim/pull/278 which passed all nominal tests. Also I can build your branch just fine. So I assume the issue is with the test. Leave it to me for now, I will get in touch if necessary.

**Comment by mashephe** [comment]
Check your AmpTools version?  This feature might be a recent addition.

----
This message was sent from my iPhone.

On Mar 22, 2023, at 8:22 AM, Peter Hurck ***@***.***> wrote:

﻿

On it.
The line that causes the error you see was pulled with #278<https://github.com/JeffersonLab/halld_sim/pull/278> which passed all nominal tests. Also I can build your branch just fine. So I assume the issue is with the test. Leave it to me for now, I will get in touch if necessary.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/make_improve_tagged_photon_energy_smearing_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/make_improve_tagged_photon_energy_smearing_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/report_improve_tagged_photon_energy_smearing_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/report_improve_tagged_photon_energy_smearing_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj

**Comment by s6pepaul** [comment]
So as far as I can see the problem is currently with the test procedure. It never starts the test build.

**Comment by rjones30** [comment]
Hello all, might this be related to the fact that github just started
requiring 2FA for all remote access yesterday? When it rains, it pours.
-Richard

**Comment by s6pepaul** [comment]
Alex has a similar suspicion. Might be the JLab 2FA?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/make_improve_tagged_photon_energy_smearing_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/make_improve_tagged_photon_energy_smearing_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/report_improve_tagged_photon_energy_smearing_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj/report_improve_tagged_photon_energy_smearing_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^improve_tagged_photon_energy_smearing_rtj

**Review by s6pepaul — APPROVED** [review]
Looks good. Can confirm it resolves issue https://github.com/JeffersonLab/halld_recon/issues/537

**Pull request merged**
