### PR TITLE
Ijaegle primex evt

### PR DESCRIPTION
**Pull request by igjaegle**
Add PrimEX eta photoproduction off Helium4

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/make_ijaegle_primex_evt.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/make_ijaegle_primex_evt.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/report_ijaegle_primex_evt.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/report_ijaegle_primex_evt.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle_primex_evt

**Comment by sdobbs** [comment]
Note that you push a commit while a build test is ongoing it will often fail like the above.  The first test is still running.

We should probably handle this case better...

**Comment by igjaegle** [comment]
Sean,

I am adding a new event generator, so the SConscript in Simulation
directory should also be changed. I will ask for a new pull shortly to
include this change.

tks ig.

**Comment by sdobbs** [comment]
Let's wait for the first test to finish, then I will start another one manually.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/make_ijaegle_primex_evt.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/make_ijaegle_primex_evt.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/report_ijaegle_primex_evt.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/report_ijaegle_primex_evt.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle_primex_evt

**Comment by sdobbs** [comment]
OK, I restarted the test build.  One thing that's not quite clear to me - what is built in the various subdirectories of the new generator you added?  are these more executables or do some libraries you link to get built?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/make_ijaegle_primex_evt.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/make_ijaegle_primex_evt.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle_primex_evt/report_ijaegle_primex_evt.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex_evt/report_ijaegle_primex_evt.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle_primex_evt

**Comment by igjaegle** [comment]
it will generate 5 executables one for the c++ and 4 for the Ilya's fortran
codes.

**Comment by sdobbs** [comment]
That's a lot, do we need them all to be built by default, or can the fortran ones be optionally built?

**Comment by igjaegle** [comment]
They are needed to calculate the differential cross-sections. But, in a
future version, it can be improved.

**Comment by sdobbs** [comment]
OK, sounds like something that can be dealt with in the future

**Pull request merged**
