### PR TITLE
Ijaegle primex

### PR DESCRIPTION
**Pull request by igjaegle**
Add a new event generator WHIZARD (https://whizard.hepforge.org/) to simulate QED backgrounds such as a e- > a e- / a e- > aa e- / a e- > e- e+e- / a e- > a a e- e+e-, and also BSM

NB: at the moment this event generator has to be used with two different compilers and env. variables:
1/ To run WHIZARD, one must use gcc 7.2 and use my env. variables and WHIZARD installation
/work/halld/home/ijaegle/Env/custom_wo.sh, it will produce LHE files (run_whizard)
2/ Switch to the default gcc and gluex env. variables
3/ Convert the LHE file to ROOT file (lhe_to_root)
4/ Produce the HDDM with gen_whizard

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^ijaegle_primex/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ijaegle_primex/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle_primex/make_ijaegle_primex.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex/make_ijaegle_primex.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle_primex/report_ijaegle_primex.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex/report_ijaegle_primex.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle_primex

**Comment by sdobbs** [comment]
If this requires a non standard environment we should discuss this at the
next software meeting and it should at least be optionally built.

**Comment by igjaegle** [comment]
The problem is the default gcc on ifarm gcc 4.8 is really old and has unresolvable compiler bugs which make crash WHIZARD. Mark is working on compiling the gluex software with another compiler that is compatible with WHIZARD (eg gcc 5.2). I created in gen_whizard two directories for run_whizard and lhe_to_root which are not compiled by default. Only gen_whizard is compiled.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle_primex/make_ijaegle_primex.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex/make_ijaegle_primex.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle_primex/report_ijaegle_primex.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex/report_ijaegle_primex.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle_primex

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle_primex/make_ijaegle_primex.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex/make_ijaegle_primex.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle_primex/report_ijaegle_primex.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex/report_ijaegle_primex.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle_primex

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^ijaegle_primex/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ijaegle_primex/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle_primex/make_ijaegle_primex.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex/make_ijaegle_primex.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle_primex/report_ijaegle_primex.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_primex/report_ijaegle_primex.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle_primex

**Comment by sdobbs** [comment]
OK, at least the code looks like it will compile in our default environment? At least the nightly build will tell us something. It does look like the SConscript for this needs more work - I don't think you require either Cernlib or AMPTOOLS?

Also, just glancing through, I have a lot of reservations with having an event generator which does a lot of work by calling external shell scripts which have some hardcoded environment in them. I would think the best way would be to factorize things in such a way that an external script could call several programs sequentially. But Mark Ito should have the last word on this.

I have compiled halld_recon at least with up to gcc 8, and I think Beni has as well, but changing the default requirements for a major software package affects many groups who build the package offsite, hence my caution on that topic.

**Comment by igjaegle** [comment]
Thank you, Sean, for your inputs. The external shell scripts are the
consequences of using two different compilers. I agree this is dirty and
this event generator has to be optimized and better fitted into the halld
software. I am open to any corrections/remarks/comments. At least as is it
is working and can be used by anyone who wishes. If we can have at least a
parallel version of the halld software on ifarm compiled with a newer (gcc
5 >=) or the newest gcc compiler that would be really great.

**Comment by somovalex** [comment]
I agree, Igal needs to work on the integration
of this event generator. But at least this
version is working (should not break
anything)
________________________________

**Comment by faustus123** [comment]
FWIW: We are using the /apps/gcc/5.3.0 compiler to build halld_recon in the counting house.
We don’t keep up a simulation build though.

Regards,
-David

-------------------------------------------------------------
David Lawrence Ph.D.
Staff Scientist, Thomas Jefferson National Accelerator Facility
Newport News, VA
davidl@jlab.org<mailto:davidl@jlab.org>
(757) 269-5567 W
(757) 746-6697 C


On Jan 19, 2020, at 9:47 PM, igjaegle <notifications@github.com<mailto:notifications@github.com>> wrote:

Thank you, Sean, for your inputs. The external shell scripts are the
consequences of using two different compilers. I agree this is dirty and
this event generator has to be optimized and better fitted into the halld
software. I am open to any corrections/remarks/comments. At least as is it
is working and can be used by anyone who wishes. If we can have at least a
parallel version of the halld software on ifarm compiled with a newer (gcc
5 >=) or the newest gcc compiler that would be really great.

**Comment by igjaegle** [comment]
Does it mean the DAQ is also using gcc 5.3.0?

tks ig.

**Comment by faustus123** [comment]
CODA DAQ is mostly Java.

Regards,
-David

-------------------------------------------------------------
David Lawrence Ph.D.
Staff Scientist, Thomas Jefferson National Accelerator Facility
Newport News, VA
davidl@jlab.org<mailto:davidl@jlab.org>
(757) 269-5567 W
(757) 746-6697 C


On Jan 21, 2020, at 1:03 PM, igjaegle <notifications@github.com<mailto:notifications@github.com>> wrote:

Does it mean the DAQ is also using gcc 5.3.0?

tks ig.

**Pull request merged**
