### PR TITLE
GammaPToNPartP set childMass and return ProductionMechanism

### PR DESCRIPTION
**Pull request by amfoda**
Adding the option to set ChildMass and access ProductionMechanism in GammaPToNPartP.

### CODE REVIEW

**Comment by mashephe** [comment]
I would prefer the setChildMass function start with a lower case to keep consistent style with other methods in the class.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/make_GammaPToNPartP_Set_Child_Range.log](https://halldweb.jlab.org/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/make_GammaPToNPartP_Set_Child_Range.log)
 Build report: [/work/halld/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/report_GammaPToNPartP_Set_Child_Range.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/report_GammaPToNPartP_Set_Child_Range.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/make_GammaPToNPartP_Set_Child_Range.log](https://halldweb.jlab.org/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/make_GammaPToNPartP_Set_Child_Range.log)
 Build report: [/work/halld/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/report_GammaPToNPartP_Set_Child_Range.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/report_GammaPToNPartP_Set_Child_Range.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/make_GammaPToNPartP_Set_Child_Range.log](https://halldweb.jlab.org/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/make_GammaPToNPartP_Set_Child_Range.log)
 Build report: [/work/halld/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/report_GammaPToNPartP_Set_Child_Range.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range/report_GammaPToNPartP_Set_Child_Range.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^GammaPToNPartP_Set_Child_Range

**Pull request closed without merging**
