### PR TITLE
Add common BeamProperties class to generators

### PR DESCRIPTION
**Pull request by jrstevenjlab**
Almost all generators use the same class for photon flux input from: CobremsGenerator, CCDB, or External ROOT file.  See https://halldweb.jlab.org/wiki/index.php/Common_beam_properties_interface_for_generators for more instructions.   Compatible with gluex_MCWrapper v2.0.4 and later.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^generator_beamProperties/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^generator_beamProperties/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^generator_beamProperties/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^generator_beamProperties/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^generator_beamProperties/make_generator_beamProperties.log](https://halldweb.jlab.org/pull_request_test/halld_sim^generator_beamProperties/make_generator_beamProperties.log)
 Build report: [/work/halld/pull_request_test/halld_sim^generator_beamProperties/report_generator_beamProperties.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^generator_beamProperties/report_generator_beamProperties.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^generator_beamProperties

**Comment by T-Britton** [comment]
Branch has conflicts? Can’t auto merge

**Comment by jrstevenjlab** [comment]
Yes, I failed to merge the latest updates from the master before the pull request (shame).  The latest commit should fix this... then it could be merged.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^generator_beamProperties/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^generator_beamProperties/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^generator_beamProperties/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^generator_beamProperties/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^generator_beamProperties/make_generator_beamProperties.log](https://halldweb.jlab.org/pull_request_test/halld_sim^generator_beamProperties/make_generator_beamProperties.log)
 Build report: [/work/halld/pull_request_test/halld_sim^generator_beamProperties/report_generator_beamProperties.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^generator_beamProperties/report_generator_beamProperties.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^generator_beamProperties

**Pull request merged**
