### PR TITLE
* introduce the new VERTEX card (see control.in) and add code to

### PR DESCRIPTION
**Pull request by rjones30**
uginit.F, hddmInput.c to support that functionality. [rtj]

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^new_beam_spot_support_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^new_beam_spot_support_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^new_beam_spot_support_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^new_beam_spot_support_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^new_beam_spot_support_rtj/make_new_beam_spot_support_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_sim^new_beam_spot_support_rtj/make_new_beam_spot_support_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_sim^new_beam_spot_support_rtj/report_new_beam_spot_support_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^new_beam_spot_support_rtj/report_new_beam_spot_support_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^new_beam_spot_support_rtj

**Review by T-Britton — APPROVED** [review]
new VERTEX card looks fine on the face of it.  Older versions will not be troubled by it....

**Comment by aaust** [comment]
If the vertex is read from ccdb, MCWrapper uses variation=mc. At the moment, the entry for this is just the default (0,0,65) without any variance. We either have to fill it or read the default variation instead.

**Comment by sdobbs** [comment]
Can we do a check with an SQLite CCDB version first?  If you want, I can create one with the correct entries.

**Pull request merged**
