### PR TITLE
Add TwoLeptonAngles for SDME analysis for J/psi --> e+ e-

### PR DESCRIPTION
**Pull request by keigo-miz**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^TwoLeptonAngles/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^TwoLeptonAngles/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^TwoLeptonAngles/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^TwoLeptonAngles/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^TwoLeptonAngles/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^TwoLeptonAngles/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^TwoLeptonAngles/make_TwoLeptonAngles.log](https://halldweb.jlab.org/pull_request_test/halld_sim^TwoLeptonAngles/make_TwoLeptonAngles.log)
 Build report: [/work/halld/pull_request_test/halld_sim^TwoLeptonAngles/report_TwoLeptonAngles.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^TwoLeptonAngles/report_TwoLeptonAngles.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^TwoLeptonAngles

**Comment by aaust** [comment]
The test which is running hd_root with multiple plugins failed. I restarted the test.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^TwoLeptonAngles/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^TwoLeptonAngles/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^TwoLeptonAngles/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^TwoLeptonAngles/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^TwoLeptonAngles/make_TwoLeptonAngles.log](https://halldweb.jlab.org/pull_request_test/halld_sim^TwoLeptonAngles/make_TwoLeptonAngles.log)
 Build report: [/work/halld/pull_request_test/halld_sim^TwoLeptonAngles/report_TwoLeptonAngles.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^TwoLeptonAngles/report_TwoLeptonAngles.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^TwoLeptonAngles

**Review by aaust — APPROVED** [review]
A copy of the infrastructure for 2 pions. Looks good.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^TwoLeptonAngles/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^TwoLeptonAngles/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^TwoLeptonAngles/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^TwoLeptonAngles/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^TwoLeptonAngles/make_TwoLeptonAngles.log](https://halldweb.jlab.org/pull_request_test/halld_sim^TwoLeptonAngles/make_TwoLeptonAngles.log)
 Build report: [/work/halld/pull_request_test/halld_sim^TwoLeptonAngles/report_TwoLeptonAngles.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^TwoLeptonAngles/report_TwoLeptonAngles.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^TwoLeptonAngles

**Pull request merged**
