### PR TITLE
mc_gen random seeds issue fixed; translator added to preselect jpsi events 

### PR DESCRIPTION
**Pull request by lihaoahil**
updated mc_gen to include option to use cpu timer in random seeding; added translator to pre-select jpsi region events.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^Hao_DEV/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^Hao_DEV/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^Hao_DEV/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^Hao_DEV/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^Hao_DEV/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^Hao_DEV/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^Hao_DEV/make_Hao_DEV.log](https://halldweb.jlab.org/pull_request_test/halld_sim^Hao_DEV/make_Hao_DEV.log)
 Build report: [/work/halld/pull_request_test/halld_sim^Hao_DEV/report_Hao_DEV.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^Hao_DEV/report_Hao_DEV.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^Hao_DEV

**Review by sdobbs — APPROVED** [review]
looks fine

**Comment by sdobbs** [comment]
build tests look like they are failing due to some problem with the test environment (missing plugins).
merging so that we can move forward with MC studies, then experts can fix the tests independently

**Comment by sdobbs** [comment]
@markito3 - looks like some problem with last night's build?

[gluex@ifarm1901 pull_request]$ ls $HALLD_RECON_HOME/Linux_RHEL7-x86_64-gcc4.8.5/plugins/
2trackskim.so                  BCAL_LEDonline.so        CCAL_online.so       CDC_TimeToDistance.so  FCALLEDTree.so                L1_online.so      ReactionEfficiency.so     ST_Propagation_Time.so
B3pi_eff_missgamma.so          BCAL_LED.so              CDC_amp.so           DAQ_online.so          FCAL_online.so                MilleFieldOff.so  ReactionFilter.so         ST_Tresolution.so
B3pi_eff_misspim.so            BCAL_LED_time.so         CDC_dedx.so          DAQTreeBCAL.so         FCAL_Pi0HFA.so                MilleFieldOn.so   RF_online.so              TAGGER_online.so
B3pi_eff_misspip.so            BCAL_online.so           CDC_drift.so         DAQTree.so             FCAL_Pi0TOF.so                PSC_online.so     RSAI_KO.so                TAGH_online.so
B3pi_eff_missprot.so           BCAL_point_calib.so      CDC_Efficiency.so    DIRC_online.so         FCAL_TimingOffsets_Primex.so  PSC_TW.so         SC_Eff.so                 TAGH_timewalk.so
BCAL_attenlength_gainratio.so  BCAL_point_time.so       CDC_expert_2.so      EPICS_dump.so          FDC_Efficiency.so             PS_E_calib.so     ST_online_efficiency.so   TAGM_clusters.so
BCAL_Eff.so                    BCAL_saturation.so       CDC_expert.so        EventTagPi0.so         FDC_InternalAlignment.so      PS_flux.so        ST_online_lowlevel.so     TAGM_online.so
BCAL_gainmatrix.so             BCAL_SiPM_saturation.so  CDC_online.so        FCAL_Hadronic_Eff.so   FDC_online.so                 PS_online.so      ST_online_multi.so        TAGM_TW.so
BCAL_Hadronic_Eff.so           BCAL_TDC_Timing.so       CDC_PerStrawReco.so  FCAL_invmass.so        FDCProjectionResiduals.so     PSPair_online.so  ST_online_tracking.so     TOF_Eff.so
BCAL_inv_mass.so               BEAM_online.so           CDC_roc_hits.so      FCAL_LED_shifts.so     HLDetectorTiming.so           PS_timing.so      ST_online_Tresolution.so  TOF_TDC_shift.so
[gluex@ifarm1901 pull_request]$ printenv HALLD_RECON_HOME
/u/scratch/gluex/nightly/2020-08-19/Linux_RHEL7-x86_64-gcc4.8.5/halld_recon
[gluex@ifarm1901 pull_request]$ ls /u/scratch/gluex/nightly/2020-08-18/Linux_RHEL7-x86_64-gcc4.8.5/halld_recon
halld_recon_prereqs_version.xml  Linux_RHEL7-x86_64-gcc4.8.5  README.md  setenv.csh  src
[gluex@ifarm1901 pull_request]$ ls /u/scratch/gluex/nightly/2020-08-18/Linux_RHEL7-x86_64-gcc4.8.5/halld_recon/Linux_RHEL7-x86_64-gcc4.8.5
bin  include  lib  plugins  python2  setenv.csh  setenv.sh
[gluex@ifarm1901 pull_request]$ ls /u/scratch/gluex/nightly/2020-08-18/Linux_RHEL7-x86_64-gcc4.8.5/halld_recon/Linux_RHEL7-x86_64-gcc4.8.5/plugins/
2trackskim.so                  bigevents_skim.so        dirc_hists.so           FCAL_TimingOffsets_Primex.so  p2pi_hists.so          RSAI_KO.so                TOF_Eff.so
b1pi_hists.so                  cal_high_energy_skim.so  DIRC_online.so          FDC_Efficiency.so             p3pi_hists.so          run_summary.so            TOF_online.so
B3pi_eff_missgamma.so          CCAL_online.so           dirc_reactions.so       FDC_InternalAlignment.so      p4pi_hists.so          SC_Eff.so                 TOF_TDC_shift.so
B3pi_eff_misspim.so            CDC_amp.so               dirc_tree.so            FDC_online.so                 pedestal_online.so     single_neutral_skim.so    TPOL_online.so
B3pi_eff_misspip.so            cdcbcal_skim.so          EPICS_dump.so           FDCProjectionResiduals.so     pi0bcalskim.so         ST_online_efficiency.so   TPOL_tree.so
B3pi_eff_missprot.so           CDC_dedx.so              es_test.so              highlevel_online.so           pi0fcalskim.so         ST_online_lowlevel.so     trackeff_hists.so
BCAL_attenlength_gainratio.so  CDC_drift.so             eta2g_primexd_skim.so   HLDetectorTiming.so           pi0fcaltofskim.so      ST_online_multi.so        trackeff_missing.so
BCAL_Eff.so                    CDC_Efficiency.so        eta6g_primexd_skim.so   imaging.so                    pid_dirc.so            ST_online_tracking.so     TrackingPulls.so
BCAL_gainmatrix.so             CDC_expert_2.so          etapi0_primexd_skim.so  L1_online.so                  ppi0gamma_hists.so     ST_online_Tresolution.so  TrackingPulls_straight.so
BCAL_Hadronic_Eff.so           CDC_expert.so            EventTagPi0.so          lowlevel_online.so            PSC_online.so          ST_Propagation_Time.so    track_skimmer.so
BCAL_inv_mass.so               CDC_online.so            evio-hddm.so            lut_dirc.so                   PSC_TW.so              ST_Tresolution.so         TRD_hists.so
BCAL_LEDonline.so              CDC_PerStrawReco.so      evio_writer.so          mcthrown_hists.so             PS_E_calib.so          st_tw_corr_auto.so        TRD_online.so
BCAL_LED.so                    CDC_roc_hits.so          exclusivepi0skim.so     mcthrown_tree.so              PS_flux.so             syncskim.so               trigger_skims.so
BCAL_LED_time.so               CDC_TimeToDistance.so    fcal_charged.so         MilleFieldOff.so              PS_online.so           TAGGER_online.so          TRIG_online.so
BCAL_online.so                 coherent_peak_skim.so    FCAL_Hadronic_Eff.so    MilleFieldOn.so               PSPair_online.so       TAGH_online.so            truth_dirc.so
BCAL_point_calib.so            compton_neutral_skim.so  FCAL_invmass.so         monitoring_hists.so           ps_skim.so             TAGH_timewalk.so          TS_scaler.so
BCAL_point_time.so             compton.so               FCAL_LED_shifts.so      occupancy_online.so           PS_timing.so           TAGM_clusters.so          twogamma_fcal_skim.so
BCAL_saturation.so             danarest.so              FCALLEDTree.so          omega_skim.so                 randomtrigger_skim.so  TAGM_online.so
BCAL_SiPM_saturation.so        DAQ_online.so            FCAL_online.so          p2gamma_hists.so              ReactionEfficiency.so  TAGM_TW.so
BCAL_TDC_Timing.so             DAQTreeBCAL.so           FCAL_Pi0HFA.so          p2k_hists.so                  ReactionFilter.so      timing_online.so
BEAM_online.so                 DAQTree.so               FCAL_Pi0TOF.so          p2pi0_hists.so                RF_online.so           TOF_calib.so

**Comment by markito3** [comment]
What is the problem?

**Comment by sdobbs** [comment]
A bunch of the plugins were not built - I don't know if it's because something timed out or what.

**Comment by markito3** [comment]
The log file for the RHEL5 build ends with:

   Connection to jlabl5 closed by remote host.

so the build never finished. Don't know why the connection got closed. I 
will try to re-start...

This does point out a problem: using the nightly build for the packages 
not under test means that it has to succeed for the pull request tests 
to work. I'm thinking that we go back to tagged versions of the 
not-being-tested packages.

**Comment by sdobbs** [comment]
Thanks, and that's fair - though then some fairly active management of the
tagged version being used may be required by whoever is in charge of that.

**Comment by markito3** [comment]
I think that that can be scripted.

**Comment by sdobbs** [comment]
Sounds fine to me, and like a good topic for the next Software meeting.

**Pull request merged**
