### PR TITLE
Ksaldan gen amp v2

### PR DESCRIPTION
**Pull request by KSaldan**
This push adds an example and instructions to generate a basic reaction using gen_amp_V2, no new code is introduced to the source code.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/make_ksaldan_gen_amp_V2.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/make_ksaldan_gen_amp_V2.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/report_ksaldan_gen_amp_V2.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/report_ksaldan_gen_amp_V2.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/make_ksaldan_gen_amp_V2.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/make_ksaldan_gen_amp_V2.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/report_ksaldan_gen_amp_V2.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/report_ksaldan_gen_amp_V2.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/make_ksaldan_gen_amp_V2.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/make_ksaldan_gen_amp_V2.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/report_ksaldan_gen_amp_V2.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/report_ksaldan_gen_amp_V2.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/make_ksaldan_gen_amp_V2.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/make_ksaldan_gen_amp_V2.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/report_ksaldan_gen_amp_V2.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/report_ksaldan_gen_amp_V2.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2

**Review by aaust — APPROVED** [review]
Useful documentation. The build test repeatedly failed for other reasons.

**Pull request merged**
