### PR TITLE
Unstable lower vertex

### PR DESCRIPTION
**Pull request by jrstevenjlab**
Add option for unstable lower vertex (e.g. Delta++) in gen_amp and gen_omegapi generators.  For omega_amplitude, separate S and D waves of 1+ into individual amplitudes.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/make_unstableLowerVertex.log](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/make_unstableLowerVertex.log)
 Build report: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/report_unstableLowerVertex.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/report_unstableLowerVertex.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^unstableLowerVertex

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/make_unstableLowerVertex.log](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/make_unstableLowerVertex.log)
 Build report: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/report_unstableLowerVertex.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/report_unstableLowerVertex.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^unstableLowerVertex

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/make_unstableLowerVertex.log](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/make_unstableLowerVertex.log)
 Build report: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/report_unstableLowerVertex.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/report_unstableLowerVertex.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^unstableLowerVertex

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/make_unstableLowerVertex.log](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/make_unstableLowerVertex.log)
 Build report: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/report_unstableLowerVertex.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/report_unstableLowerVertex.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^unstableLowerVertex

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/make_unstableLowerVertex.log](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/make_unstableLowerVertex.log)
 Build report: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/report_unstableLowerVertex.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/report_unstableLowerVertex.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^unstableLowerVertex

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/make_unstableLowerVertex.log](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/make_unstableLowerVertex.log)
 Build report: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/report_unstableLowerVertex.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/report_unstableLowerVertex.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^unstableLowerVertex

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/make_unstableLowerVertex.log](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/make_unstableLowerVertex.log)
 Build report: [/work/halld/pull_request_test/halld_sim^unstableLowerVertex/report_unstableLowerVertex.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^unstableLowerVertex/report_unstableLowerVertex.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^unstableLowerVertex

**Review by gleasonc — APPROVED** [review]
I have tested this with eta pi- delta++ and the results look good.

**Pull request merged**
