### PR TITLE
Ijaegle gen ee

### PR DESCRIPTION
**Pull request by igjaegle**
Add configuation example for LH2 target in gen_ee

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^ijaegle_gen_ee/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_gen_ee/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ijaegle_gen_ee/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_gen_ee/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle_gen_ee/make_ijaegle_gen_ee.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_gen_ee/make_ijaegle_gen_ee.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle_gen_ee/report_ijaegle_gen_ee.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_gen_ee/report_ijaegle_gen_ee.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle_gen_ee

**Comment by markdalton** [comment]
These files are not visible /work/halld/home/ijaegle/src/gluex/dev/halld_sim/src/programs/Simulation/gen_whizard/data/data_Be_pair.pl
/work/halld/home/ijaegle/src/gluex/dev/halld_sim/src/programs/Simulation/gen_whizard/data/data_Be_trip.pl 

I suggest 
$HALLD_SIM_HOME/src/gluex/dev/halld_sim/src/programs/Simulation/gen_whizard/data/data_H_pair.pl
$HALLD_SIM_HOME/src/gluex/dev/halld_sim/src/programs/Simulation/gen_whizard/data/data_H_trip.pl

**Comment by igjaegle** [comment]
Good point, done.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^ijaegle_gen_ee/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_gen_ee/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ijaegle_gen_ee/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_gen_ee/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ijaegle_gen_ee/make_ijaegle_gen_ee.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_gen_ee/make_ijaegle_gen_ee.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ijaegle_gen_ee/report_ijaegle_gen_ee.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ijaegle_gen_ee/report_ijaegle_gen_ee.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ijaegle_gen_ee

**Review by markdalton — APPROVED** [review]

**Pull request merged**
