### PR TITLE
gen amp v2

### PR DESCRIPTION
**Pull request by KSaldan**
Addition of gen amp V2 which generates N-body phase space with the option to accumulate events in the correct regions of phase space. The documentation is attached to this pull request.
[GlueX_Fixed_Target_Generator.pdf](https://github.com/JeffersonLab/halld_sim/files/14826374/GlueX_Fixed_Target_Generator.pdf)

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/make_ksaldan_gen_amp_V2.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/make_ksaldan_gen_amp_V2.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/report_ksaldan_gen_amp_V2.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/report_ksaldan_gen_amp_V2.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2

**Comment by aaust** [comment]
The compilation throws a warning that the members in the initializer list 
https://github.com/JeffersonLab/halld_sim/blob/c878b50baca6cad04b3d3d326fb493315697d051/src/libraries/AMPTOOLS_MCGEN/ProductionMechanism.cc#L23-L24
do not appear in the same order as in the class definition
https://github.com/JeffersonLab/halld_sim/blob/c878b50baca6cad04b3d3d326fb493315697d051/src/libraries/AMPTOOLS_MCGEN/ProductionMechanism.h#L57-L61

**Comment by mashephe** [comment]
I believe that warning existed in the master before.  The class wasn't changed by the PR in question, but I had to apply Peter's changes to the branch because I needed to change his changes to BW generator.

I just pushed a change to the branch that reorders initializers.. can you rerun the test?

Matt


On Apr 1, 2024, at 3:33 PM, Alexander Austregesilo ***@***.***> wrote:



The compilation throws a warning that the members in the initializer list
https://github.com/JeffersonLab/halld_sim/blob/c878b50baca6cad04b3d3d326fb493315697d051/src/libraries/AMPTOOLS_MCGEN/ProductionMechanism.cc#L23-L24
do not appear in the same order as in the class definition
https://github.com/JeffersonLab/halld_sim/blob/c878b50baca6cad04b3d3d326fb493315697d051/src/libraries/AMPTOOLS_MCGEN/ProductionMechanism.h#L57-L61

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/make_ksaldan_gen_amp_V2.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/make_ksaldan_gen_amp_V2.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2/report_ksaldan_gen_amp_V2.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ksaldan_gen_amp_V2/report_ksaldan_gen_amp_V2.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ksaldan_gen_amp_V2

**Review by aaust — APPROVED** [review]
Good additional functionality, approving for further testing

**Comment by aaust** [comment]
@KSaldan Could you please link the documentation elsewhere? You could add a wiki page for gen_amp_v2 here, for example:
https://halldweb.jlab.org/wiki/index.php/Event_generators

**Comment by mashephe** [comment]
I've added a link to the documentation

**Pull request merged**
