### PR TITLE
Correct another bug

### PR DESCRIPTION
**Pull request by igjaegle**
Correct another bug.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^compt_corr/make_compt_corr.log](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/make_compt_corr.log)
 Build report: [/work/halld/pull_request_test/halld_sim^compt_corr/report_compt_corr.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/report_compt_corr.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^compt_corr

**Comment by igjaegle** [comment]
I can compile it locally. So I do not know the failure cause and I cannot access the build log build report txt files,

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^compt_corr/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^compt_corr/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^compt_corr/make_compt_corr.log](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/make_compt_corr.log)
 Build report: [/work/halld/pull_request_test/halld_sim^compt_corr/report_compt_corr.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/report_compt_corr.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^compt_corr

**Comment by andrsmit** [comment]
I can compile the code, but when I run it I'm getting an error message from line 228 which I did not have before this most recent change. This is what I run:

sd_compton bases-init.dbf test 11.6061 1000 primex_tagh.txt 74 1

And this is the error message:

At line 228 of file programs/Simulation/gen_primex_compton/sd_compton/sd_compton.F (unit = 20, file = 'test.bin')
Fortran runtime error: Write exceeds length of DIRECT access record

**Comment by igjaegle** [comment]
ok I understand error, I will correct it shortly.

**Comment by sdobbs** [comment]
For what it's worth, the test failure is probably because you pushed some
commits to the pull request branch while the tests were ongoing - the
system doesn't handle such collisions cleanly.

**Comment by igjaegle** [comment]
This error is now corrected and it seems to work for me now. Let me know if otherwise for you.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^compt_corr/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^compt_corr/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^compt_corr/make_compt_corr.log](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/make_compt_corr.log)
 Build report: [/work/halld/pull_request_test/halld_sim^compt_corr/report_compt_corr.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^compt_corr/report_compt_corr.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^compt_corr

**Review by andrsmit — APPROVED** [review]

**Pull request merged**
