### PR TITLE
FP32

### PR DESCRIPTION
**Pull request by mashephe**
These changes allow the option for one to use single precision computation in AmpTools for event-level quantities.  The default behavior should not change.  However, if the AmpTools library is complied in single precision the build system will detect this and set the correct preprocessor definitions so that compilation of amplitude classes is also done in single precision.

### CODE REVIEW

**Comment by mashephe** [comment]
I'm working on resolving the conflicts now.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^FP32/make_FP32.log](https://halldweb.jlab.org/pull_request_test/halld_sim^FP32/make_FP32.log)
 Build report: [/work/halld/pull_request_test/halld_sim^FP32/report_FP32.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FP32/report_FP32.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^FP32

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^FP32/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FP32/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^FP32/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FP32/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^FP32/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^FP32/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^FP32/make_FP32.log](https://halldweb.jlab.org/pull_request_test/halld_sim^FP32/make_FP32.log)
 Build report: [/work/halld/pull_request_test/halld_sim^FP32/report_FP32.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FP32/report_FP32.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^FP32

**Comment by mashephe** [comment]
I think I've resolved the conflicts, but the build test has failed.  From the log it appears there might have been a collision in testing the branches.  Can somebody reinitiate the test?

**Comment by mashephe** [comment]
bump... can someone run the build test and consider this PR?

**Comment by sdobbs** [comment]
Sorry for the delay on this - I restarted the build test.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^FP32/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FP32/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^FP32/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^FP32/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^FP32/make_FP32.log](https://halldweb.jlab.org/pull_request_test/halld_sim^FP32/make_FP32.log)
 Build report: [/work/halld/pull_request_test/halld_sim^FP32/report_FP32.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^FP32/report_FP32.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^FP32

**Review by sdobbs — APPROVED** [review]
Looks good to me - Lawrence Ng has been using the branch extensively as well.

**Pull request merged**
