### PR TITLE
EvtGen 

### PR DESCRIPTION
**Pull request by sdobbs**
Initial implementation of using the EvtGen event generator to simulate particle decays.  This has been implemented in two locations:
- integrated as option in genEtaRegge
- new "afterburner"-style program decay_evtgen which is run on events generated from other generators

First report at August 6, 2019 Software Meeting (see slides there), additional annoucements and docs to come.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_evtgen/make_sdobbs_evtgen.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_evtgen/make_sdobbs_evtgen.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_evtgen/report_sdobbs_evtgen.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_evtgen/report_sdobbs_evtgen.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_evtgen

**Comment by sdobbs** [comment]
This is due to an environment problem in the test build, working on it...

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_evtgen/make_sdobbs_evtgen.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_evtgen/make_sdobbs_evtgen.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_evtgen/report_sdobbs_evtgen.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_evtgen/report_sdobbs_evtgen.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_evtgen

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^sdobbs_evtgen/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_evtgen/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^sdobbs_evtgen/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_evtgen/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_evtgen/make_sdobbs_evtgen.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_evtgen/make_sdobbs_evtgen.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_evtgen/report_sdobbs_evtgen.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_evtgen/report_sdobbs_evtgen.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_evtgen

**Pull request merged**
