### PR TITLE
Comment out save command. Needs review.

### PR DESCRIPTION
**Pull request by markito3**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^version_upgrade_fixes/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^version_upgrade_fixes/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^version_upgrade_fixes/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^version_upgrade_fixes/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^version_upgrade_fixes/make_version_upgrade_fixes.log](https://halldweb.jlab.org/pull_request_test/halld_sim^version_upgrade_fixes/make_version_upgrade_fixes.log)
 Build report: [/work/halld/pull_request_test/halld_sim^version_upgrade_fixes/report_version_upgrade_fixes.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^version_upgrade_fixes/report_version_upgrade_fixes.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^version_upgrade_fixes

**Review by rjones30 — COMMENTED** [review]
Why?

**Comment by markito3** [comment]
GCC 8.3 gives an error trying to compile gphad.F. Removing the SAVE command allows compilation. Behavior of the routine should not change since we always throw the -fno-automatic switch to gfortran.

I believe that the error gets thrown because of EQUIVALENCE between a local variable and a member of a common block. This construction is coming in via [cernlib/2005/include/geant321/gcbank.inc](http://ftp.riken.jp/cernlib/download/2006_source/include/geant321/gcbank.inc). An example of the error is:

    Compiling  [programs/Simulation/HDGeant/gelhad/gphad.F]
    /data/scratch/beta_1.0/gluex_top_c7_dts8/cernlib/2005/include/geant321/gcbank.inc:23:19:
     
           EQUIVALENCE (Q(1),IQ(1),LQ(9)),(LQ(1),LMAIN),(IWS(1),WS(1))
                       1
    Error: COMMON attribute conflicts with SAVE attribute in 'q' at (1)

Other errors are reported.

The problem is that WS appears in the common block and the compiler does not like this construction if IWS is SAVEd. Remove the SAVE, and it compiles.

I had to patch another similar construction in CERNLIB itself. I followed the prescription from ALICE described [here](https://github.com/alisw/alidist/issues/1345).

**Comment by markito3** [comment]
Note: I was worried that local variables would not be static if the SAVE was removed. That is why I added the phrase "needs review" in the title of this pull request. Since then I realized that the -fno-automatic thing makes all local variable static in any case.

**Comment by rjones30** [comment]
Sounds reasonable, let's do it -rtj

**Review by rjones30 — APPROVED** [review]

**Pull request merged**
