### PR TITLE
Modified double regge

### PR DESCRIPTION
**Pull request by ReBarsotti**
Updated double regge amplitudes to the latest version: 

-Is now GPU compatible
-Is split into an amplitude for the fast eta and the fast pi

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^ModifiedDoubleRegge/make_ModifiedDoubleRegge.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ModifiedDoubleRegge/make_ModifiedDoubleRegge.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ModifiedDoubleRegge/report_ModifiedDoubleRegge.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ModifiedDoubleRegge/report_ModifiedDoubleRegge.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ModifiedDoubleRegge

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^ModifiedDoubleRegge/make_ModifiedDoubleRegge.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ModifiedDoubleRegge/make_ModifiedDoubleRegge.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ModifiedDoubleRegge/report_ModifiedDoubleRegge.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ModifiedDoubleRegge/report_ModifiedDoubleRegge.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ModifiedDoubleRegge

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^ModifiedDoubleRegge/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ModifiedDoubleRegge/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ModifiedDoubleRegge/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ModifiedDoubleRegge/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ModifiedDoubleRegge/make_ModifiedDoubleRegge.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ModifiedDoubleRegge/make_ModifiedDoubleRegge.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ModifiedDoubleRegge/report_ModifiedDoubleRegge.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ModifiedDoubleRegge/report_ModifiedDoubleRegge.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ModifiedDoubleRegge

**Review by mashephe — APPROVED** [review]
Looks good!

**Pull request merged**
