### PR TITLE
gen omegapi

### PR DESCRIPTION
**Pull request by amfoda**
a generator for b1(1235)->omega pi0

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^gen_omegapi/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^gen_omegapi/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^gen_omegapi/make_gen_omegapi.log](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/make_gen_omegapi.log)
 Build report: [/work/halld/pull_request_test/halld_sim^gen_omegapi/report_gen_omegapi.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/report_gen_omegapi.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^gen_omegapi

**Comment by aaust** [comment]
The generator has to be added to the SConscript file in the parent directory:
https://github.com/JeffersonLab/halld_sim/blob/master/src/programs/Simulation/SConscript

Could you please also add an example config file in the directory to test the generator?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^gen_omegapi/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^gen_omegapi/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^gen_omegapi/make_gen_omegapi.log](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/make_gen_omegapi.log)
 Build report: [/work/halld/pull_request_test/halld_sim^gen_omegapi/report_gen_omegapi.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/report_gen_omegapi.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^gen_omegapi

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^gen_omegapi/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^gen_omegapi/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^gen_omegapi/make_gen_omegapi.log](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/make_gen_omegapi.log)
 Build report: [/work/halld/pull_request_test/halld_sim^gen_omegapi/report_gen_omegapi.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/report_gen_omegapi.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^gen_omegapi

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^gen_omegapi/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^gen_omegapi/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^gen_omegapi/make_gen_omegapi.log](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/make_gen_omegapi.log)
 Build report: [/work/halld/pull_request_test/halld_sim^gen_omegapi/report_gen_omegapi.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/report_gen_omegapi.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^gen_omegapi

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^gen_omegapi/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^gen_omegapi/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^gen_omegapi/make_gen_omegapi.log](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/make_gen_omegapi.log)
 Build report: [/work/halld/pull_request_test/halld_sim^gen_omegapi/report_gen_omegapi.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^gen_omegapi/report_gen_omegapi.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^gen_omegapi

**Pull request merged**
