### PR TITLE
Pol moments

### PR DESCRIPTION
**Pull request by mariana-khach**
I have added code for calculation of polarized moments in terms of partial waves

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^Pol_Moments/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^Pol_Moments/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^Pol_Moments/make_Pol_Moments.log](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/make_Pol_Moments.log)
 Build report: [/work/halld/pull_request_test/halld_sim^Pol_Moments/report_Pol_Moments.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/report_Pol_Moments.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^Pol_Moments

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^Pol_Moments/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^Pol_Moments/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^Pol_Moments/make_Pol_Moments.log](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/make_Pol_Moments.log)
 Build report: [/work/halld/pull_request_test/halld_sim^Pol_Moments/report_Pol_Moments.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/report_Pol_Moments.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^Pol_Moments

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^Pol_Moments/make_Pol_Moments.log](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/make_Pol_Moments.log)
 Build report: [/work/halld/pull_request_test/halld_sim^Pol_Moments/report_Pol_Moments.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/report_Pol_Moments.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^Pol_Moments

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^Pol_Moments/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^Pol_Moments/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^Pol_Moments/make_Pol_Moments.log](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/make_Pol_Moments.log)
 Build report: [/work/halld/pull_request_test/halld_sim^Pol_Moments/report_Pol_Moments.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/report_Pol_Moments.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^Pol_Moments

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^Pol_Moments/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^Pol_Moments/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^Pol_Moments/make_Pol_Moments.log](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/make_Pol_Moments.log)
 Build report: [/work/halld/pull_request_test/halld_sim^Pol_Moments/report_Pol_Moments.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^Pol_Moments/report_Pol_Moments.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^Pol_Moments

**Review by aaust — APPROVED** [review]
I tested it with a simple test case and it worked

**Pull request merged**
