### PR TITLE
Changes to VecPs Plotter

### PR DESCRIPTION
**Pull request by edbarriga**
Vecps_plotter now looks at the number of particles and counts the number of pions.
VecPSPlotGenerator now computes the phase difference and uses the name of the sums to assign the reflectivity.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^update_VecPsPlotter/make_update_VecPsPlotter.log](https://halldweb.jlab.org/pull_request_test/halld_sim^update_VecPsPlotter/make_update_VecPsPlotter.log)
 Build report: [/work/halld/pull_request_test/halld_sim^update_VecPsPlotter/report_update_VecPsPlotter.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^update_VecPsPlotter/report_update_VecPsPlotter.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^update_VecPsPlotter

**Review by edbarriga — COMMENTED** [review]
I added the missing declaration of phaseDiffNames.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^update_VecPsPlotter/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^update_VecPsPlotter/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^update_VecPsPlotter/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^update_VecPsPlotter/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^update_VecPsPlotter/make_update_VecPsPlotter.log](https://halldweb.jlab.org/pull_request_test/halld_sim^update_VecPsPlotter/make_update_VecPsPlotter.log)
 Build report: [/work/halld/pull_request_test/halld_sim^update_VecPsPlotter/report_update_VecPsPlotter.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^update_VecPsPlotter/report_update_VecPsPlotter.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^update_VecPsPlotter

**Comment by mashephe** [comment]
It looks like the desire here is to have a common plot generator that works for a number of different topologies.  One way to handle this a little more cleanly is to use the keyword functionality of the config file.  You can probably do something like this in your config file:

keyword finalState 1 1
finalState omegaEta

This declares a new keyword "finalState" that requires exactly 1 arguments (minumum 1 maximum 1).  Then in that projectEvent method you can do something like:

string finalState = cfgInfo()->userKeywordArguments( "finalState" )[0][0];

Then check finalState using strcmp and behave appropriately.

The ConfigurationInfo object has all the information about the fit setup.  See ConfigurationInfo.h.  You may be able to get what you need there without even using the keyword mechanism.  This is also how we fetch the polarization arguments to the amplitude in the case you want to properly plot multiple polarization states simultaneously.

If we keep all the Vec PS plotting capability in this class, then it probably makes sense to try to figure out how to organize it best.  Alternatively, analysts could maintain plot generators for their own "flavors" of VecPS analysis.  I think there is merit in doing that also.  Everyone will inevitably want to look at different things.

A final note, the new projectEvent method in AmpTools has a 2nd string argument that is the name of the reaction.  This is essential.  There is just one PlotGenerator for the whole job and so in multiple-reaction fits it is important to know which reaction the event is coming from.  (Again this is important for simultaneous fits to multiple polarization states.)  See the etapiPlotGenerator for an example.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^update_VecPsPlotter/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^update_VecPsPlotter/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^update_VecPsPlotter/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^update_VecPsPlotter/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^update_VecPsPlotter/make_update_VecPsPlotter.log](https://halldweb.jlab.org/pull_request_test/halld_sim^update_VecPsPlotter/make_update_VecPsPlotter.log)
 Build report: [/work/halld/pull_request_test/halld_sim^update_VecPsPlotter/report_update_VecPsPlotter.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^update_VecPsPlotter/report_update_VecPsPlotter.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^update_VecPsPlotter

**Comment by jrstevenjlab** [comment]
The recent commit addresses @mashephe's suggestion to utilize the ConfigurationInfo object to utilize different options in the plotter which is similar to what's done in the VecPs amplitude currently.  Analysts may prefer to spin off their own version of a plotter for a specific analysis but this at least puts it in a functional state for the existing "flavors" of VecPs analyses for those wishing to use it.

**Review by jrstevenjlab — APPROVED** [review]
Sorry again for the slow response, but I think this address's the suggestions so I'll add my approval to the original pull request by @edbarriga.  But someone else should check and do the merge since I'm contributing as well.

**Pull request merged**
