### PR TITLE
FixedTargetGenerator class

### PR DESCRIPTION
**Pull request by mashephe**
This PR includes a new class for MC generation called FixedTargetGenerator.  This class is designed for GlueX t-channel reactions.  It allows the user to specify and arbitrary number of particles coming from the upper (N_u) and lower (N_l) vertex.  By default it will generate correct multi body phase space for N = N_u + N_l particles.  The user can then seed the generation with Breit-Wigner distributions at the upper and lower vertex and an exponential t distribution.  The generator will provide appropriate weights to recover N-body phase space in these cases.

In this PR the class added to the AMPTOOLS_MCGEN library but it has not been implemented in any of the programs that we use for generation.  Therefore, the functionality of the programs in halld_sim is unchanged with this PR.  I would like to add the class to the repository first.  We can then use subsequent PR's to merge changes that use it.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/make_shepherd_phasespace_gen.log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/make_shepherd_phasespace_gen.log)
 Build report: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/report_shepherd_phasespace_gen.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/report_shepherd_phasespace_gen.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen

**Comment by mashephe** [comment]
There is a root script that can be used to generate some 5-body phase space here:

/work/halld/home/shepherd/gen_ps/testFTGen.C

One needs to load the FixedTargetGenerator class into ROOT prior to this:

.L FixedTargetGenerator.cc+

You may need to add some symbolic links to resolve the include paths in that file.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/make_shepherd_phasespace_gen.log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/make_shepherd_phasespace_gen.log)
 Build report: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/report_shepherd_phasespace_gen.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/report_shepherd_phasespace_gen.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/make_shepherd_phasespace_gen.log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/make_shepherd_phasespace_gen.log)
 Build report: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/report_shepherd_phasespace_gen.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/report_shepherd_phasespace_gen.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/make_shepherd_phasespace_gen.log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/make_shepherd_phasespace_gen.log)
 Build report: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/report_shepherd_phasespace_gen.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/report_shepherd_phasespace_gen.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen

**Comment by jrstevenjlab** [comment]
Something minor, when compiling there's a complaint about redefining "PI" with what another variable in AmpTools.  Could this be addressed or use pi from ROOT's TMath that some other amplitudes use?

libraries/AMPTOOLS_MCGEN/FixedTargetGenerator.h:13:0: warning: "PI" redefined [enabled by default]
 #define PI 3.14159
 ^
In file included from /home/jrsteven/work2/analysisGluexI/builds/AmpTools/AmpTools/IUAmpTools/Amplitude.h:48:0,
                 from libraries/AMPTOOLS_AMPS/omegapi_amplitude.h:5,
                 from programs/Simulation/gen_omegapi_ps/gen_omegapi_ps.cc:21:
/home/jrsteven/work2/analysisGluexI/builds/AmpTools/AmpTools/GPUManager/GPUCustomTypes.h:123:0: note: this is the location of the previous definition
 #define PI 3.141592653589793

**Comment by jrstevenjlab** [comment]
Also, setUpperVtxMasses and setLowerVtxMasses seem to be in the header as placeholders but not defined in the class.  Could these be added?

**Comment by mashephe** [comment]
OK - I think I took care of these and just pushed the change to the branch.

Matt

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/make_shepherd_phasespace_gen.log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/make_shepherd_phasespace_gen.log)
 Build report: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/report_shepherd_phasespace_gen.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/report_shepherd_phasespace_gen.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/make_shepherd_phasespace_gen.log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/make_shepherd_phasespace_gen.log)
 Build report: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/report_shepherd_phasespace_gen.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/report_shepherd_phasespace_gen.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen

**Comment by jrstevenjlab** [comment]
Last comment from me: the default `Kinematics` object returned by other generators includes the beam energy as the 0th element of the vector of TLorentzVectors, since that's how most of our config files and amplitudes are implemented.  Currently only the final state particles are in the returned vector.  Could the beam be added here to stick with the standard practice?

**Comment by mashephe** [comment]
Yes, good point.  I just pushed the change.  This will add the beam by default but the user has the option to turn this behavior off if desired.

Does this work as you'd like it to?

Matt

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/make_shepherd_phasespace_gen.log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/make_shepherd_phasespace_gen.log)
 Build report: [/work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen/report_shepherd_phasespace_gen.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_phasespace_gen/report_shepherd_phasespace_gen.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^shepherd_phasespace_gen

**Comment by jrstevenjlab** [comment]
Yep, the latest commit makes the returned particle vector consistent with our other generator tools

**Review by jrstevenjlab — APPROVED** [review]
I was able to run a hacked version of gen_omegapi that generates reasonable output with this new generator.  Merging to move forward with development.

**Pull request merged**
