### PR TITLE
Add non-default option to generate with uniform t-distribution, minor…

### PR DESCRIPTION
**Pull request by jonzarling**
… histogram updates.

### CODE REVIEW

**Comment by jonzarling** [comment]
Here's what the t-distribution looked like previously with default config:
image


Generating flat distribution with new command line options "-U -tmin0.0 -tmax2.0000":
image

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/make_jzGenEtaRegge_flat_t.log](https://halldweb.jlab.org/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/make_jzGenEtaRegge_flat_t.log)
 Build report: [/work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/report_jzGenEtaRegge_flat_t.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/report_jzGenEtaRegge_flat_t.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t

**Comment by jonzarling** [comment]
u-channel should be working now too, with the caveat that the distribution won't quite be flat towards the high end, since t_max is dependent on beam energy.

image

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/make_jzGenEtaRegge_flat_t.log](https://halldweb.jlab.org/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/make_jzGenEtaRegge_flat_t.log)
 Build report: [/work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/report_jzGenEtaRegge_flat_t.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/report_jzGenEtaRegge_flat_t.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t

**Review by staylorjlab — COMMENTED** [review]
tmax in code is not consistent with Usage (-3 vs -2).
Do you need to call CrossSection twice for each trial for the flat-t distribution?

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/make_jzGenEtaRegge_flat_t.log](https://halldweb.jlab.org/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/make_jzGenEtaRegge_flat_t.log)
 Build report: [/work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/report_jzGenEtaRegge_flat_t.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/report_jzGenEtaRegge_flat_t.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/make_jzGenEtaRegge_flat_t.log](https://halldweb.jlab.org/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/make_jzGenEtaRegge_flat_t.log)
 Build report: [/work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/report_jzGenEtaRegge_flat_t.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^jzGenEtaRegge_flat_t/report_jzGenEtaRegge_flat_t.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^jzGenEtaRegge_flat_t

**Review by staylorjlab — APPROVED** [review]

**Comment by staylorjlab** [comment]
Looks like a useful feature for eta studies

**Pull request merged**
