### PR TITLE
Faster amplitude for rho/phi SDMEs with GPU kernel

### PR DESCRIPTION
**Pull request by aaust**
- considerably faster on CPU due to pre-computed user variables
- up to 200x faster on GPU
- polarization value is either fixed or taken from TPol histogram
- polarization orientation cannot be varied by fit, left as AmpTools parameter for consistency

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/make_aaust_TwoPiAnglesFast.log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/make_aaust_TwoPiAnglesFast.log)
 Build report: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/report_aaust_TwoPiAnglesFast.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/report_aaust_TwoPiAnglesFast.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast

**Comment by mashephe** [comment]
Is there any reason to keep the original TwoPiAngles amplitude?  Should we maybe just replace it with this one?

Matt

**Comment by aaust** [comment]
I would prefer to keep the original amplitude in order to be able to fit the orientation angle for systematic studies. In this implementation, the calculation of Phi is done within calcUserVars, so the parameter polangle can no longer be varied.

**Comment by mashephe** [comment]
Alex,

I think this could be accommodated with just a little change.

I believe kBigPhi is a difference of one angle (which varies with each event) with the polarization angle.  You can compute the angle that event dependent and store it as a user variable and then compute the difference with polAngle in the calcAmplitude function.  It is negligible CPU cost to subtract two numbers.  This would then be the best of both worlds:  you get all the speedup and can still float the polarization angle.

(There is a proliferation of amplitudes in halld_sim... it would be good to keep only the best, most functional ones as these are better examples if someone needs to write something new.)

Matt

**Comment by mashephe** [comment]
Also as written the amplitude in PR registered polAngle as a parameter.   So the framework thinks it is a parameter, but in reality (as you pointed out) it cannot be varied.  The suggestion below fixes that.

**Comment by aaust** [comment]
Capital Phi is the angle between the polarization direction and the production plane, and is computed with cross products and atan2. You were probably thinking of Psi=Phi-phi which is used in the simplified decay asymmetry, but it is not used here.
I will benchmark how much performance we loose by performing the calculation of Phi in the amplitude. Maybe I find a better solution.

**Comment by mashephe** [comment]
> On Mar 11, 2022, at 5:21 PM, Alex Austregesilo ***@***.***> wrote:
> 
> Capital Phi is the angle between the polarization direction and the production plane, and is computed with cross products and atan2.

Yes... I thought this reduced to just a difference between the production plane in the lab and the polarization plane in the lab, but maybe this is not correct... or maybe it isn't generally correct.

It seems like the angle between the beam vector and the z axis enters in in a way that I don't understand.  (That is zero in the GJ system and it all makes sense.)  I wonder if there is a way simplify this.  May need to sketch it out on a sheet of paper.

I quick test to my suggestion would be to take, say the, 45 degree data and print out BigPhi for a few events.  Then compute with polAngle = 0 in that formula and see if the result is shifted by 45 degrees.  If so, then it demonstrates you can just put this offset back in in the calcAmplitude function.  As noted above, maybe that works in one frame but not in general.

(I'd try to avoid creating ROOT vector objects in the calcAmplitude function if you can avoid it.)

Matt

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/make_aaust_TwoPiAnglesFast.log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/make_aaust_TwoPiAnglesFast.log)
 Build report: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/report_aaust_TwoPiAnglesFast.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/report_aaust_TwoPiAnglesFast.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/make_aaust_TwoPiAnglesFast.log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/make_aaust_TwoPiAnglesFast.log)
 Build report: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/report_aaust_TwoPiAnglesFast.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/report_aaust_TwoPiAnglesFast.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/make_aaust_TwoPiAnglesFast.log](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/make_aaust_TwoPiAnglesFast.log)
 Build report: [/work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/report_aaust_TwoPiAnglesFast.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^aaust_TwoPiAnglesFast/report_aaust_TwoPiAnglesFast.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^aaust_TwoPiAnglesFast

**Review by mashephe — APPROVED** [review]

**Pull request merged**
