### PR TITLE
Modify genEtaRegge to play better with MCWrapper

### PR DESCRIPTION
**Pull request by sdobbs**
Allow for 0 final state particles in case we want an afterburner like decay_evtgen to do the actual decaying

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix

**Comment by sdobbs** [comment]
ignore further tests, working on fixing a bug or two

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix

**Comment by sdobbs** [comment]
this is what it's supposed to do!  -eq != -ne

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix

**Comment by sdobbs** [comment]
all the tests are being completed successfully!  now just need to change the reporting to reflect that

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/make_sdobbs_etaregge_fix.log)
 Build report: [/work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^sdobbs_etaregge_fix/report_sdobbs_etaregge_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^sdobbs_etaregge_fix

**Comment by sdobbs** [comment]
Success!  Also someone should merge this PR

**Review by staylorjlab — APPROVED** [review]

**Comment by staylorjlab** [comment]
Looks good to me.

**Pull request merged**
