### PR TITLE
Ecal libs

### PR DESCRIPTION
**Pull request by somovalex**
Low-level ECAL reconstruction

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^ecal_libs/make_ecal_libs.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ecal_libs/make_ecal_libs.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ecal_libs/report_ecal_libs.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ecal_libs/report_ecal_libs.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ecal_libs

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^ecal_libs/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ecal_libs/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^ecal_libs/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ecal_libs/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ecal_libs/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ecal_libs/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ecal_libs/make_ecal_libs.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ecal_libs/make_ecal_libs.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ecal_libs/report_ecal_libs.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ecal_libs/report_ecal_libs.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ecal_libs

**Comment by aaust** [comment]
The first test failed yesterday, because it was built against halld_recon that did not know about ECAL yet. Today's test built fine, but could not run hdgeant4. The nightly build of hdgeant4 failed because of the missing ECAL lib.

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^ecal_libs/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ecal_libs/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^ecal_libs/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ecal_libs/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^ecal_libs/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^ecal_libs/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^ecal_libs/make_ecal_libs.log](https://halldweb.jlab.org/pull_request_test/halld_sim^ecal_libs/make_ecal_libs.log)
 Build report: [/work/halld/pull_request_test/halld_sim^ecal_libs/report_ecal_libs.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^ecal_libs/report_ecal_libs.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^ecal_libs

**Review by staylorjlab — APPROVED** [review]
Although the build check failed, I have been able to confirm that it does actually build and I checked a handful of simulated photon events using hdgeant to verify that ECAL hits are indeed being generated.

**Comment by igjaegle** [comment]
It is working for me

**Pull request merged**
