### PR TITLE
reinitializePars by default

### PR DESCRIPTION
**Pull request by jrstevenjlab**
For fits with randomized starting parameters, execute reinitializePars() to restore parameter values from configuration file, so they're not carried over between randomized fit iterations.  Addresses behavior described in issue #281

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_sim^reinitializeParsDefault/make_reinitializeParsDefault.log](https://halldweb.jlab.org/pull_request_test/halld_sim^reinitializeParsDefault/make_reinitializeParsDefault.log)
 Build report: [/work/halld/pull_request_test/halld_sim^reinitializeParsDefault/report_reinitializeParsDefault.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^reinitializeParsDefault/report_reinitializeParsDefault.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^reinitializeParsDefault

**Review by mashephe — APPROVED** [review]
This change looks good.  The AmpToolsInterface should behave as desired.

**Comment by aaust** [comment]
The build fails because there is a new problem with the nightly builds on /u/scratch. I will restart the test once the version set is in place.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^reinitializeParsDefault/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^reinitializeParsDefault/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^reinitializeParsDefault/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^reinitializeParsDefault/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^reinitializeParsDefault/make_reinitializeParsDefault.log](https://halldweb.jlab.org/pull_request_test/halld_sim^reinitializeParsDefault/make_reinitializeParsDefault.log)
 Build report: [/work/halld/pull_request_test/halld_sim^reinitializeParsDefault/report_reinitializeParsDefault.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^reinitializeParsDefault/report_reinitializeParsDefault.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^reinitializeParsDefault

**Pull request merged**
