### PR TITLE
Ppgenvecps

### PR DESCRIPTION
**Pull request by s6pepaul**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_sim^PPgenvecps/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^PPgenvecps/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_sim^PPgenvecps/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^PPgenvecps/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^PPgenvecps/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^PPgenvecps/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^PPgenvecps/make_PPgenvecps.log](https://halldweb.jlab.org/pull_request_test/halld_sim^PPgenvecps/make_PPgenvecps.log)
 Build report: [/work/halld/pull_request_test/halld_sim^PPgenvecps/report_PPgenvecps.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^PPgenvecps/report_PPgenvecps.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^PPgenvecps

**Comment by jrstevenjlab** [comment]
Looks like the same failure mode as https://github.com/JeffersonLab/halld_sim/pull/206 and these changes should definitely be independent of hdgeant(4)

**Review by jrstevenjlab — APPROVED** [review]
Thanks for adding these generalizations Peter, looks good to me.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^PPgenvecps/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^PPgenvecps/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^PPgenvecps/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^PPgenvecps/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^PPgenvecps/make_PPgenvecps.log](https://halldweb.jlab.org/pull_request_test/halld_sim^PPgenvecps/make_PPgenvecps.log)
 Build report: [/work/halld/pull_request_test/halld_sim^PPgenvecps/report_PPgenvecps.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^PPgenvecps/report_PPgenvecps.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^PPgenvecps

**Pull request merged**
