### PR TITLE
Flatte amplitude

### PR DESCRIPTION
**Pull request by maltealbrecht**
initial version of Flatte amplitude - up for code review.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^malte_Flatte/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Flatte/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^malte_Flatte/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Flatte/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^malte_Flatte/make_malte_Flatte.log](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Flatte/make_malte_Flatte.log)
 Build report: [/work/halld/pull_request_test/halld_sim^malte_Flatte/report_malte_Flatte.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Flatte/report_malte_Flatte.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^malte_Flatte

**Review by mashephe — COMMENTED** [review]
To be technically correct, it would be good to change the result of the isGPUEnabled member function in the header to "false".  It appears that you are not providing a GPU kernel for this amplitude so, at present, it is not GPU enabled.

In the case one wants to float couplings in a fit, this is an amplitude that would also likely benefit substantially from the use of user variables to store the masses and breakup momenta.  I don't think this enhancement has to be made at this point, but if people start really using this amplitude with floating parameters we should do it to save a lot of CPU.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^malte_Flatte/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Flatte/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^malte_Flatte/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Flatte/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^malte_Flatte/make_malte_Flatte.log](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Flatte/make_malte_Flatte.log)
 Build report: [/work/halld/pull_request_test/halld_sim^malte_Flatte/report_malte_Flatte.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Flatte/report_malte_Flatte.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^malte_Flatte

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^malte_Flatte/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Flatte/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^malte_Flatte/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Flatte/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^malte_Flatte/make_malte_Flatte.log](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Flatte/make_malte_Flatte.log)
 Build report: [/work/halld/pull_request_test/halld_sim^malte_Flatte/report_malte_Flatte.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^malte_Flatte/report_malte_Flatte.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^malte_Flatte

**Review by mashephe — APPROVED** [review]
Looks good!

**Pull request merged**
