### PR TITLE
Shepherd omega sdme

### PR DESCRIPTION
**Pull request by mashephe**
These are some older changes to the amplitudes for omega SDMEs.  They provide a more descriptive (correct) name in the radiative decay case and overall provide optimized memory use and speed for both decay modes of the omega.  This will require @markdalton to make a few changes to config files in order to use the new naming, but I think it is mostly find/replace.  This was optimization work that was done last summer but never quite made it into the master branch.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^shepherd_omega_SDME/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_omega_SDME/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^shepherd_omega_SDME/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_omega_SDME/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^shepherd_omega_SDME/make_shepherd_omega_SDME.log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_omega_SDME/make_shepherd_omega_SDME.log)
 Build report: [/work/halld/pull_request_test/halld_sim^shepherd_omega_SDME/report_shepherd_omega_SDME.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_omega_SDME/report_shepherd_omega_SDME.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^shepherd_omega_SDME

**Comment by mashephe** [comment]
Could I bump this up on the radar.  Understandably, I think the proposed reviewers are looking for @markdalton  to comment because the changes will affect him most.  I see now that Keigo is proposing an addition of amplitude and this will probably cause a merge conflict with fit.cc that will need resolution.

**Comment by markdalton** [comment]
From my side, I think you should go ahead with the merge.  I'll make the mods to my config files.  Is there an example config to point to?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_sim^shepherd_omega_SDME/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_omega_SDME/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_sim^shepherd_omega_SDME/tests/log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_omega_SDME/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_sim^shepherd_omega_SDME/make_shepherd_omega_SDME.log](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_omega_SDME/make_shepherd_omega_SDME.log)
 Build report: [/work/halld/pull_request_test/halld_sim^shepherd_omega_SDME/report_shepherd_omega_SDME.txt](https://halldweb.jlab.org/pull_request_test/halld_sim^shepherd_omega_SDME/report_shepherd_omega_SDME.txt)
 Location of build: /work/halld/pull_request_test/halld_sim^shepherd_omega_SDME

**Review by aaust — APPROVED** [review]
I can't see anything wrong with it but I did not perform a fit to test this change.

**Pull request merged**
